{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "matomo.fullname" . }}-archive
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
    app.kubernetes.io/component: archive
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "matomo.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: archive
        spec:
          {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ include "matomo.serviceAccountName" . }}
          {{- end }}
          automountServiceAccountToken: false
          {{- with .Values.matomo.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          containers:
          - name: archive
            image: curlimages/curl:8.5.0
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              echo "[$(date)] Starting Matomo archive processing via HTTP..."
              
              # Wait for Matomo to be ready
              echo "Checking Matomo service availability..."
              for i in $(seq 1 10); do
                if curl -f -s http://{{ include "matomo.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local/index.php > /dev/null; then
                  echo "✓ Matomo service is ready"
                  break
                fi
                echo "Waiting for Matomo service... attempt $i/10"
                sleep 10
              done
              
              # Trigger archive processing via HTTP with token
              echo "Triggering archive processing..."
              ARCHIVE_URL="http://{{ include "matomo.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local/misc/cron/archive.php?token_auth=$ARCHIVE_TOKEN"
              
              if curl -f -s -X GET "$ARCHIVE_URL" -H "User-Agent: Matomo-Archive-CronJob" > /tmp/archive_output.txt; then
                echo "✓ Archive processing triggered successfully"
                echo "Archive output:"
                cat /tmp/archive_output.txt
              else
                echo "⚠️ Archive processing may have issues, checking response..."
                cat /tmp/archive_output.txt || echo "No output received"
              fi
              
              echo "[$(date)] Archive processing completed"
            env:
            - name: ARCHIVE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "matomo.fullname" . }}
                  key: archive-token
            {{- with .Values.cronjob.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            volumeMounts:
            - name: tmp
              mountPath: /tmp
          volumes:
          - name: tmp
            emptyDir: {}
{{- end }}
