{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "matomo.fullname" . }}-archive
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
    app.kubernetes.io/component: archive
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "matomo.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: archive
        spec:
          {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ include "matomo.serviceAccountName" . }}
          {{- end }}
          automountServiceAccountToken: false
          {{- with .Values.matomo.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          containers:
          - name: archive
            image: {{ .Values.matomo.image.registry }}/{{ .Values.matomo.image.repository }}:{{ .Values.matomo.image.tag }}
            imagePullPolicy: {{ .Values.matomo.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - |
              echo "[$(date)] Starting Matomo archive processing via HTTP..."
              
              # Wait for Matomo service to be ready
              echo "Checking Matomo service availability..."
              for i in $(seq 1 30); do
                if curl -f -s "http://{{ include "matomo.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local" > /dev/null 2>&1; then
                  echo "✓ Matomo service is ready"
                  break
                fi
                echo "Waiting for Matomo service... attempt $i/30"
                sleep 10
              done
              
              # Trigger archive processing via HTTP (no volume mount needed)
              echo "Triggering archive via HTTP endpoint..."
              ARCHIVE_URL="http://{{ include "matomo.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local/misc/cron/archive.php?token=${ARCHIVE_TOKEN}"
              
              if curl -f -s "$ARCHIVE_URL" -o /tmp/archive_output.txt; then
                echo "✓ Archive processing completed successfully"
                cat /tmp/archive_output.txt
                echo ""
                echo "[$(date)] Archive processing completed"
                exit 0
              else
                echo "⚠️ Archive processing failed"
                cat /tmp/archive_output.txt 2>/dev/null || echo "No output"
                exit 1
              fi
            env:
            - name: MATOMO_DATABASE_HOST
              value: {{ include "matomo.fullname" . }}-mariadb
            - name: MATOMO_DATABASE_USERNAME
              value: {{ .Values.mariadb.auth.username }}
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "matomo.fullname" . }}-mariadb
                  key: mariadb-password
            - name: MATOMO_DATABASE_DBNAME
              value: {{ .Values.mariadb.auth.database }}
            - name: ARCHIVE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "matomo.fullname" . }}
                  key: archive-token
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
            volumeMounts:
            - name: tmp
              mountPath: /tmp
          volumes:
          - name: tmp
            emptyDir: {}
{{- end }}
