apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "matomo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "matomo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: matomo
        image: {{ .Values.matomo.image.registry }}/{{ .Values.matomo.image.repository }}:{{ .Values.matomo.image.tag }}
        imagePullPolicy: {{ .Values.matomo.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
        env:
        - name: MATOMO_DATABASE_HOST
          value: {{ include "matomo.fullname" . }}-mariadb
        - name: MATOMO_DATABASE_USERNAME
          value: {{ .Values.mariadb.auth.username }}
        - name: MATOMO_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "matomo.fullname" . }}-mariadb
              key: mariadb-password
        - name: MATOMO_DATABASE_DBNAME
          value: {{ .Values.mariadb.auth.database }}
        - name: MATOMO_DATABASE_TABLES_PREFIX
          value: "matomo_"
        - name: MATOMO_DATABASE_ADAPTER
          value: "PDO\\MYSQL"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: matomo-data
          mountPath: /var/www/html
        - name: tmp-volume
          mountPath: /tmp
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: matomo-data
        persistentVolumeClaim:
          claimName: {{ include "matomo.fullname" . }}
      - name: tmp-volume
        emptyDir: {}
