apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
type: Opaque
data:
  matomo-username: {{ .Values.matomo.admin.username | b64enc | quote }}
  matomo-password: {{ .Values.matomo.admin.password | b64enc | quote }}
  matomo-email: {{ .Values.matomo.admin.email | b64enc | quote }}
  archive-token: {{ .Values.matomo.archiveToken | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.fullname" . }}-mariadb
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-username: {{ .Values.mariadb.auth.username | b64enc | quote }}
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
