# WeOwn Enterprise Vaultwarden Configuration
# Security-first, cohort-replicable deployment

# Global configuration
global:
  # Cohort member customization - REQUIRED
  subdomain: "vault"  # e.g., "vault" for vault.example.com
  domain: ""  # REQUIRED: Set during deployment (e.g., example.com)

# cert-manager configuration
certManager:
  enabled: true
  clusterIssuer: "letsencrypt-prod"
  email: ""  # REQUIRED: Set during deployment (e.g., admin@example.com)
  server: "https://acme-v02.api.letsencrypt.org/directory"
  
# Image configuration
image:
  repository: vaultwarden/server
  tag: "1.30.3"
  pullPolicy: IfNotPresent

# Security configuration
security:
  # Pod Security Context (non-root, restricted)
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  
  # Container Security Context
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE

  # Network Policies (zero-trust)
  networkPolicy:
    enabled: true
    ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        ports:
        - protocol: TCP
          port: 8080

# Vaultwarden configuration
vaultwarden:
  # Admin configuration
  admin:
    # Admin token will be generated and stored in Kubernetes Secret
    # Set via: kubectl create secret generic vaultwarden-admin --from-literal=token="your-secure-token"
    existingSecret: "vaultwarden-admin"
    secretKey: "token"
  
  # Application settings
  config:
    websocketEnabled: true
    showPasswordHint: true
    signupsAllowed: true  # Disable after initial setup
    invitationsAllowed: true
    emergencyAccessAllowed: true
    sendEnabled: false  # Disable Bitwarden Send for security
    webVaultEnabled: true
    
  # Domain configuration (auto-generated from global values)
  domain: ""  # Will be set to https://{{ .Values.global.subdomain }}.{{ .Values.global.domain }}

# Persistence
persistence:
  enabled: true
  storageClass: "do-block-storage"
  size: 10Gi
  accessMode: ReadWriteOnce

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Ingress configuration with TLS
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  # Extra authentication options for subdomain security
  extraAuth:
    enabled: false  # Set to true to enable additional authentication
    type: "basic"   # Options: "basic", "oauth", "whitelist"
    # Basic Auth (if type: "basic")
    basicAuth:
      username: "admin"
      password: ""  # Will be auto-generated if empty
    # IP Whitelist (if type: "whitelist") 
    whitelist:
      enabled: false
      ips: []  # Example: ["192.168.1.0/24", "10.0.0.0/8"]
    # OAuth (if type: "oauth") - Advanced users only
    oauth:
      enabled: false
      provider: "github"  # github, google, etc.
  hosts:
    - host: ""  # Will be set to {{ .Values.global.subdomain }}.{{ .Values.global.domain }}
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: vaultwarden-tls
      hosts:
        - ""  # Will be set to {{ .Values.global.subdomain }}.{{ .Values.global.domain }}

# Resource limits (optimized based on actual usage: 1m CPU, 17Mi Memory)
resources:
  limits:
    cpu: 200m      # Reduced from 500m (still 200x actual usage)
    memory: 256Mi  # Reduced from 512Mi (still 15x actual usage)
  requests:
    cpu: 50m       # Reduced from 100m (still 50x actual usage)
    memory: 64Mi   # Reduced from 128Mi (still 4x actual usage)

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false  # Single replica for data consistency
  minReplicas: 1
  maxReplicas: 1

# Health checks
livenessProbe:
  httpGet:
    path: /alive
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /alive
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# RBAC
rbac:
  create: true
  
# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Monitoring (Prometheus integration)
monitoring:
  enabled: false  # Enable when Prometheus is available
  serviceMonitor:
    enabled: false
