apiVersion: v2
name: wordpress
description: Enterprise-grade WordPress with enhanced security, zero-trust networking, and automated TLS
type: application
version: 3.2.0
appVersion: "6.8.3"

keywords:
- wordpress
- cms
- blog
- php
- mariadb

home: https://github.com/WeOwnNetwork/ai
sources:
- https://github.com/WeOwnNetwork/ai/tree/main/wordpress

maintainers:
- name: Enterprise WordPress
  email: admin@example.com

# No external dependencies - using official MariaDB image via custom StatefulSet

annotations:
  category: CMS
  licenses: Apache-2.0
