{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email | quote }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}
          podTemplate:
            spec:
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              containers:
              - name: acme-solver
                securityContext:
                  readOnlyRootFilesystem: true
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                resources:
                  limits:
                    cpu: 100m
                    memory: 128Mi
                  requests:
                    cpu: 50m
                    memory: 64Mi
{{- end }}
