{{- if .Values.wordpress.autoscaling.enabled }}
apiVersion: {{ include "wordpress.hpa.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wordpress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: scaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wordpress.fullname" . }}
  minReplicas: {{ .Values.wordpress.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.wordpress.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.wordpress.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.wordpress.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.wordpress.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.wordpress.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.wordpress.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.wordpress.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
