{{- if .Values.mariadbOfficial.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.mariadbOfficial.auth.rootPassword | b64enc | quote }}
  mariadb-password: {{ .Values.mariadbOfficial.auth.password | b64enc | quote }}
{{- end }}
