{{- if not (lookup "cert-manager.io/v1" "ClusterIssuer" "" "letsencrypt-prod") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email | default "admin@weown.xyz" }}
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
