{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ include "nextcloud.namespace" . }}
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nextcloud.fullname" . }}
  namespace: {{ include "nextcloud.namespace" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "nextcloud.serviceAccountName" . }}
  namespace: {{ include "nextcloud.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "nextcloud.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
