{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.redisServiceName" . }}
  namespace: {{ include "nextcloud.namespace" . }}
  labels:
    {{- include "nextcloud.redisLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nextcloud.redisLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nextcloud.redisLabels" . | nindent 8 }}
    spec:
      {{- if .Values.redis.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: redis
        image: "{{ include "nextcloud.redisImageRepository" . }}"
        imagePullPolicy: IfNotPresent
        {{- if .Values.redis.containerSecurityContext }}
        securityContext:
          {{- toYaml .Values.redis.containerSecurityContext | nindent 10 }}
        {{- end }}
        command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        - --appendonly
        - "no"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "nextcloud.redisSecretName" . }}
              key: REDIS_PASSWORD
        ports:
        - containerPort: 6379
          name: redis
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --no-auth-warning
            - -a
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.redisServiceName" . }}
  namespace: {{ include "nextcloud.namespace" . }}
  labels:
    {{- include "nextcloud.redisLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    {{- include "nextcloud.redisLabels" . | nindent 4 }}
{{- end }}
