apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.serviceName" . }}
  namespace: {{ include "nextcloud.namespace" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nextcloud.service.type }}
  ports:
    - port: {{ .Values.nextcloud.service.port }}
      targetPort: {{ .Values.nextcloud.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
