[prod]
node1 ansible_host=129.212.176.158
node2 ansible_host=129.212.189.67
node3 ansible_host=165.245.131.10

[prod:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
