{{- if .Values.backup.enabled }}
---
# ServiceAccount for backup CronJob
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anythingllm.fullname" . }}-backup
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
automountServiceAccountToken: true

---
# Role for backup operations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "anythingllm.fullname" . }}-backup
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
rules:
  # Read access to pods (to find AnythingLLM pod)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  
  # Execute commands in pods (for backup operations)
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  
  # Read access to PVCs (for backup verification)
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]

---
# RoleBinding to grant backup ServiceAccount the backup role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "anythingllm.fullname" . }}-backup
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "anythingllm.fullname" . }}-backup
subjects:
  - kind: ServiceAccount
    name: {{ include "anythingllm.fullname" . }}-backup
    namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- end }}
