# Generated by Django 5.2.16 on 2026-08-03 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('body_md', models.TextField(help_text='Full agreement text (markdown)')),
                ('active', models.BooleanField(default=False, help_text='The one shown for new signatures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier1_pct', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('tier2_pct', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'get_latest_by': 'effective_from',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='referral code used in signup links', max_length=32, unique=True)),
                ('stripe_connect_account_id', models.CharField(blank=True, help_text='Stripe Connect Express account for payouts (empty until onboarded)', max_length=64)),
                ('tier1_pct_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override of the global tier-1 %, leave empty for default', max_digits=5, null=True)),
                ('tier2_pct_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active', models.BooleanField(default=False, help_text='Only set after their contract is signed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text="Tier-2 beneficiary of this affiliate's referrals", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.affiliate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc_user_id', models.CharField(blank=True, help_text='Keycloak user UUID (sub claim)', max_length=64)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('instance_slug', models.CharField(blank=True, help_text='weown-fleet tenant slug once provisioned (empty until then)', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, help_text='Affiliate whose link/code this customer signed up through', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.affiliate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='incomplete', max_length=16)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_sha256', models.CharField(max_length=64)),
                ('signed_name', models.CharField(help_text='Name typed by the signer', max_length=120)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signer_ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.affiliate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contracttemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('affiliate', 'template'), name='one_signature_per_version')],
            },
        ),
    ]
