# Generated by Django 5.2.16 on 2026-08-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_instance_status_customer_instance_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitconfig',
            name='monthly_cogs_cents',
            field=models.PositiveIntegerField(default=0, help_text='Cost of goods sold per instance-month, in CENTS (droplet, LLM keys, support overhead) — subtracted with Stripe fees before splits'),
        ),
        migrations.CreateModel(
            name='SplitPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, max_length=64)),
                ('tier', models.PositiveSmallIntegerField()),
                ('gross_cents', models.PositiveIntegerField()),
                ('stripe_fee_cents', models.PositiveIntegerField()),
                ('cogs_cents', models.PositiveIntegerField()),
                ('profit_cents', models.IntegerField()),
                ('pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cut_cents', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('skipped_no_account', 'Skipped — affiliate has no Connect account'), ('skipped_no_profit', 'Skipped — no profit on this invoice')], max_length=24)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='core.affiliate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('invoice_id', 'affiliate', 'tier'), name='one_payout_per_invoice_leg')],
            },
        ),
    ]
