# Generated by Django 5.2.16 on 2026-08-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_splitconfig_monthly_cogs_cents_splitpayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatecontract',
            name='signer_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='contracttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='one_active_contract_template'),
        ),
        migrations.AddConstraint(
            model_name='splitconfig',
            constraint=models.CheckConstraint(condition=models.Q(('tier1_pct__gte', 0), ('tier1_pct__lte', 100)), name='tier1_pct_0_100'),
        ),
        migrations.AddConstraint(
            model_name='splitconfig',
            constraint=models.CheckConstraint(condition=models.Q(('tier2_pct__gte', 0), ('tier2_pct__lte', 100)), name='tier2_pct_0_100'),
        ),
    ]
