# Generated by Django 5.2.17 on 2026-08-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trial_and_customer_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatecontract',
            name='signer_forwarded_for',
            field=models.CharField(blank=True, help_text='Raw X-Forwarded-For chain as received. signer_ip is the rightmost hop (the one our own proxy appended, and the only one a client cannot forge); this keeps the whole chain for forensics.', max_length=300),
        ),
        migrations.AddField(
            model_name='customercontract',
            name='signer_forwarded_for',
            field=models.CharField(blank=True, help_text='Raw X-Forwarded-For chain as received. signer_ip is the rightmost hop (the one our own proxy appended, and the only one a client cannot forge); this keeps the whole chain for forensics.', max_length=300),
        ),
    ]
