# Generated by Django 5.2.17 on 2026-08-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_signature_forwarded_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitpayout',
            name='charge_id',
            field=models.CharField(blank=True, db_index=True, help_text='The charge that funded this payout. Recorded so a refund or dispute — which arrives as a CHARGE event — can find the legs it has to claw back without re-deriving the invoice.', max_length=64),
        ),
        migrations.CreateModel(
            name='SplitReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(db_index=True, help_text='The refund/dispute event that triggered this clawback', max_length=64)),
                ('reason', models.CharField(help_text='refund | dispute', max_length=32)),
                ('amount_cents', models.IntegerField(help_text='Clawed back by THIS reversal')),
                ('charge_refunded_cents', models.IntegerField(help_text='Cumulative amount refunded on the charge when this was computed')),
                ('status', models.CharField(choices=[('reversed', 'Reversed — funds clawed back'), ('skipped_nothing_owed', 'Skipped — already fully reversed'), ('skipped_not_paid', 'Skipped — leg never paid out'), ('failed', 'Reversal failed — see error')], max_length=24)),
                ('stripe_reversal_id', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='core.splitpayout')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stripe_event_id', 'payout'), name='one_reversal_per_event_leg')],
            },
        ),
    ]
