{{- if .Values.auth.enableBasicAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-auth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    component: auth
type: Opaque
data:
  auth: {{ htpasswd .Values.n8n.auth.user .Values.n8n.auth.password | b64enc }}
{{- end }}
