// {{ project_name }} customer dashboard — zero-dependency Node server.
// (Plain JS, no jinja vars: all instance config arrives via environment,
// injected at container start by the Infisical entrypoint wrapper.)
//
// WHAT THIS IS: the customer's ONLY surface. They authenticate HERE (never to
// AnythingLLM), and this server proxies scoped actions to the ALLM API with
// the admin Developer API key held server-side. Two sections:
//   Public  -> workspace WS_PUBLIC_SLUG  (grounds the website embed widget)
//   Private -> workspace WS_PRIVATE_SLUG (their business docs + private chat)
//
// Zero npm dependencies by design: no supply chain, no install step at deploy.
// Uploads and chat are streamed/proxied raw — this server never parses
// multipart bodies, it just authenticates, scopes, and forwards.
//
// Required env (Infisical): ALLM_ADMIN_API_KEY, DASHBOARD_PASSWORD_HASH
// (sha256 hex of the customer password), DASHBOARD_SESSION_SECRET.
// Optional env: DASHBOARD_CUSTOMER_EMAIL, WS_PUBLIC_SLUG, WS_PRIVATE_SLUG,
// EMBED_ID, EMBED_ALLOWLIST_DOMAINS, PUBLIC_DOMAIN, ALLM_URL, PORT, BASE_PATH,
// DASHBOARD_STATE_DIR, UPLOAD_ALLOWED_EXT, UPLOAD_MAX_BYTES.
'use strict';
const http = require('http');
const https = require('https');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const PORT = parseInt(process.env.PORT || '3000', 10);
const BASE = process.env.BASE_PATH || '/app';
const ALLM_URL = process.env.ALLM_URL || 'http://anythingllm:3001';
const API_KEY = process.env.ALLM_ADMIN_API_KEY || '';
// Customer-facing billing portal (subscription, invoices, affiliate earnings).
// Optional: instances without it simply don't show the billing link.
const BILLING_URL = process.env.BILLING_URL || '';
// scrypt (memory-hard KDF, built into node crypto — no npm dep). Format:
// scrypt$<salthex>$<hashhex>. Never a fast hash: a leaked Infisical value must
// not be brute-forceable. Generated by scripts/bootstrap-product.sh.
const PW_HASH = process.env.DASHBOARD_PASSWORD_HASH || '';
function verifyPassword(pw) {
  const parts = PW_HASH.split('$');
  if (parts.length !== 3 || parts[0] !== 'scrypt') return false;
  let salt, expected, actual;
  try {
    salt = Buffer.from(parts[1], 'hex');
    expected = Buffer.from(parts[2], 'hex');
    actual = crypto.scryptSync(pw || '', salt, expected.length);
  } catch { return false; }
  return actual.length === expected.length && crypto.timingSafeEqual(actual, expected);
}
const SESSION_SECRET = process.env.DASHBOARD_SESSION_SECRET || '';
const CUSTOMER_EMAIL = (process.env.DASHBOARD_CUSTOMER_EMAIL || '').toLowerCase();
const WS = { public: process.env.WS_PUBLIC_SLUG || 'ws-public', private: process.env.WS_PRIVATE_SLUG || 'ws-private' };
const EMBED_ID = process.env.EMBED_ID || '';
const PUBLIC_DOMAIN = process.env.PUBLIC_DOMAIN || '';
const VERSION = process.env.DASHBOARD_VERSION || 'v0';

SEE_FULL_CONTENT_IN_WORKSPACE_MCP_ARGS_UPDATE_0_ARGS_JSON_LENGTH_45584