// {{ project_name }} customer dashboard — zero-dependency Node server.
// (Plain JS, no jinja vars: all instance config arrives via environment,
// injected at container start by the Infisical entrypoint wrapper.)
//
// WHAT THIS IS: the customer's ONLY surface. They authenticate HERE (never to
// AnythingLLM), and this server proxies scoped actions to the ALLM API with
// the admin Developer API key held server-side. Two sections:
//   Public  -> workspace WS_PUBLIC_SLUG  (grounds the website embed widget)
//   Private -> workspace WS_PRIVATE_SLUG (their business docs + private chat)
//
// Zero npm dependencies by design: no supply chain, no install step at deploy.
// Uploads and chat are streamed/proxied raw — this server never parses
// multipart bodies, it just authenticates, scopes, and forwards.
//
// Required env (Infisical): ALLM_ADMIN_API_KEY, DASHBOARD_PASSWORD_HASH
// (sha256 hex of the customer password), DASHBOARD_SESSION_SECRET.
// Optional env: DASHBOARD_CUSTOMER_EMAIL, WS_PUBLIC_SLUG, WS_PRIVATE_SLUG,
// EMBED_ID, EMBED_ALLOWLIST_DOMAINS, PUBLIC_DOMAIN, ALLM_URL, PORT, BASE_PATH,
// DASHBOARD_STATE_DIR, UPLOAD_ALLOWED_EXT, UPLOAD_MAX_BYTES, ALLM_DOCUMENTS_PATH
// (read-only mount of ALLM's storage/documents dir — powers full text previews).
'use strict';
const http = require('http');
const https = require('https');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const PORT = parseInt(process.env.PORT || '3000', 10);
const BASE = process.env.BASE_PATH || '/app';
const ALLM_URL = process.env.ALLM_URL || 'http://anythingllm:3001';
const API_KEY = process.env.ALLM_ADMIN_API_KEY || '';
// Customer-facing billing portal (subscription, invoices, affiliate earnings).
// Optional: instances without it simply don't show the billing link.
const BILLING_URL = process.env.BILLING_URL || '';
// scrypt (memory-hard KDF, built into node crypto — no npm dep). Format:
// scrypt$<salthex>$<hashhex>. Never a fast hash: a leaked Infisical value must
// not be brute-forceable. Generated by scripts/bootstrap-product.sh.
const PW_HASH = process.env.DASHBOARD_PASSWORD_HASH || '';
function verifyPassword(pw) {
  const parts = PW_HASH.split('$');
  if (parts.length !== 3 || parts[0] !== 'scrypt') return false;
  let salt, expected, actual;
  try {
    salt = Buffer.from(parts[1], 'hex');
    expected = Buffer.from(parts[2], 'hex');
    actual = crypto.scryptSync(pw || '', salt, expected.length);
  } catch { return false; }
  return actual.length === expected.length && crypto.timingSafeEqual(actual, expected);
}
const SESSION_SECRET = process.env.DASHBOARD_SESSION_SECRET || '';
const CUSTOMER_EMAIL = (process.env.DASHBOARD_CUSTOMER_EMAIL || '').toLowerCase();
const WS = { public: process.env.WS_PUBLIC_SLUG || 'ws-public', private: process.env.WS_PRIVATE_SLUG || 'ws-private' };
const EMBED_ID = process.env.EMBED_ID || '';
const PUBLIC_DOMAIN = process.env.PUBLIC_DOMAIN || '';
const VERSION = process.env.DASHBOARD_VERSION || 'v0';

// ── embed domain allowlist ───────────────────────────────────────────────────
// AnythingLLM will answer an embed from ANY website unless the embed carries an
// allowlist (a NULL allowlist means allow-all), so the customer's bot — and
// their capped LLM budget — is only theirs once this list is set. The list is
// seeded by provisioning (EMBED_ALLOWLIST_DOMAINS) and owned by the customer
// from their first save here, so adding a second website never needs an
// operator. It can never be emptied: this instance's own origin is always in it.
//
// ALLM compares the browser's Origin header to the stored strings EXACTLY, so
// every entry must be "scheme://host[:port]" — lower-cased, no path, no trailing
// slash, no wildcards (ALLM does not support them).
const STATE_DIR = process.env.DASHBOARD_STATE_DIR || '/state';
const DOMAINS_FILE = path.join(STATE_DIR, 'embed-domains.json');
const normOrigin = (raw) => {
  let s = String(raw || '').trim().toLowerCase();
  if (!s) return null;
  if (!/^https?:\/\//.test(s)) s = `https://${s}`;
  let u; try { u = new URL(s); } catch { return null; }
  if (!u.hostname.includes('.') || /[^a-z0-9.-]/.test(u.hostname)) return null;
  return `${u.protocol}//${u.hostname}${u.port ? `:${u.port}` : ''}`;
};
const dedupe = (list) => [...new Set(list.filter(Boolean))];
const SELF_ORIGIN = normOrigin(PUBLIC_DOMAIN);
const seedDomains = () => dedupe((process.env.EMBED_ALLOWLIST_DOMAINS || '').split(',').map(normOrigin));
const readDomains = () => {
  try { return dedupe(JSON.parse(fs.readFileSync(DOMAINS_FILE, 'utf8')).domains.map(normOrigin)); }
  catch { return seedDomains(); }
};
const writeDomains = (list) => {
  try {
    fs.mkdirSync(STATE_DIR, { recursive: true });
    fs.writeFileSync(DOMAINS_FILE, JSON.stringify({ domains: list, savedAt: new Date().toISOString() }, null, 2));
    return true;
  } catch (e) { console.error('[dashboard] could not persist embed domains:', e.message); return false; }
};

// ── booking CTA (embed companion button) ─────────────────────────────────────
// Practice owners can surface a "Book a call" affordance next to the website
// chat launcher. Persisted in STATE_DIR like embed-domains / locks; atomic
// rename so a crash mid-write never leaves a truncated file.
// Snippet policy (deliberate): always keep data-no-sponsor="true" so AnythingLLM
// sponsor chrome stays off. When a booking URL is set we inject a companion
// floating button near the launcher — clearer than dual sponsor+floating CTAs.
const BOOKING_FILE = path.join(STATE_DIR, 'booking.json');
const DEFAULT_BOOKING_LABEL = 'Book a call';
const validateBookingUrl = (raw) => {
  const s = String(raw || '').trim();
  if (!s) return { ok: true, url: '' };
  let u;
  try { u = new URL(s); } catch { return { ok: false, error: 'not a valid URL — use https://…' }; }
  if (u.protocol === 'javascript:' || u.protocol === 'data:' || u.protocol === 'vbscript:')
    return { ok: false, error: 'that URL scheme is not allowed' };
  // Never accept userinfo — https://user:pass@host would leak into the public snippet.
  if (u.username || u.password)
    return { ok: false, error: 'booking URL must not include a username or password' };
  if (u.protocol === 'https:') return { ok: true, url: u.toString() };
  const host = (u.hostname || '').toLowerCase();
  if (u.protocol === 'http:' && (host === 'localhost' || host === '127.0.0.1' || host === '[::1]'))
    return { ok: true, url: u.toString() };
  return { ok: false, error: 'booking URL must be https (http only allowed for localhost)' };
};
const readBooking = () => {
  try {
    const j = JSON.parse(fs.readFileSync(BOOKING_FILE, 'utf8'));
    const rawUrl = typeof j.url === 'string' ? j.url.trim() : '';
    const label = typeof j.label === 'string' ? j.label.trim() : '';
    // Re-validate on read so a hand-edited / stale booking.json cannot inject
    // javascript:/data: (or non-localhost http) into the public companion CTA.
    const checked = validateBookingUrl(rawUrl);
    if (!checked.ok) {
      console.error('[dashboard] booking.json URL rejected on read — treating as empty:', checked.error);
      return { url: '', label: '' };
    }
    const url = checked.url;
    return { url, label: label || (url ? DEFAULT_BOOKING_LABEL : '') };
  } catch (e) {
    if (e.code !== 'ENOENT') console.error('[dashboard] booking.json unreadable — treating as empty:', e.message);
    return { url: '', label: '' };
  }
};
const writeBooking = (url, label) => {
  try {
    fs.mkdirSync(STATE_DIR, { recursive: true });
    const tmp = `${BOOKING_FILE}.${process.pid}.tmp`;
    const payload = { url: url || '', label: label || '', savedAt: new Date().toISOString() };
    fs.writeFileSync(tmp, JSON.stringify(payload, null, 2));
    fs.renameSync(tmp, BOOKING_FILE);
    return true;
  } catch (e) { console.error('[dashboard] could not persist booking:', e.message); return false; }
};

const escAttr = (s) => String(s || '').replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
/** JSON.stringify safe inside an HTML <script> raw-text block (</script> breakout). */
const jsonForScript = (v) => JSON.stringify(v).replace(/</g, '\\u003c').replace(/>/g, '\\u003e');

// ── embed appearance (logo + curated themes) ─────────────────────────────────
// High-taste presets only — not a free-form theme builder. Optional accent
// override changes data-button-color alone; bubble colors stay with the preset.
// Custom logo lives under STATE_DIR/embed-brand/; metadata in embed-appearance.json.
const APPEARANCE_FILE = path.join(STATE_DIR, 'embed-appearance.json');
const BRAND_DIR = path.join(STATE_DIR, 'embed-brand');
const LOGO_MAX_BYTES = 1.5 * 1024 * 1024; // 1.5 MB
const LOGO_EXTS = new Set(['png', 'jpg', 'jpeg', 'webp', 'svg']);
const LOGO_MIME = {
  png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg',
  webp: 'image/webp', svg: 'image/svg+xml',
};
const CHAT_ICONS = new Set(['plus', 'chatBubble', 'support', 'search2', 'search', 'magic']);
const EMBED_THEMES = {
  weown: {
    id: 'weown', name: 'WeOwn', blurb: 'Signature blue — calm on dark or light sites',
    buttonColor: '#00A3FF', userBgColor: '#00A3FF', assistantBgColor: '#1e293b', chatIcon: 'chatBubble',
  },
  harbor: {
    id: 'harbor', name: 'Harbor Gold', blurb: 'Warm gold launcher — demo / premium feel',
    buttonColor: '#c9a227', userBgColor: '#c9a227', assistantBgColor: '#1c1917', chatIcon: 'magic',
  },
  midnight: {
    id: 'midnight', name: 'Midnight', blurb: 'Deep slate launcher with soft assistant bubbles',
    buttonColor: '#334155', userBgColor: '#475569', assistantBgColor: '#0f172a', chatIcon: 'chatBubble',
  },
  softlight: {
    id: 'softlight', name: 'Soft Light', blurb: 'Light neutrals for bright marketing sites',
    buttonColor: '#0369a1', userBgColor: '#075985', assistantBgColor: '#f1f5f9', chatIcon: 'plus',
  },
  forest: {
    id: 'forest', name: 'Forest', blurb: 'Quiet greens — practices and advisory firms',
    buttonColor: '#2d6a4f', userBgColor: '#40916c', assistantBgColor: '#1b4332', chatIcon: 'support',
  },
};
const DEFAULT_THEME_ID = 'weown';
const isHexColor = (s) => /^#[0-9A-Fa-f]{6}$/.test(String(s || ''));
/** Relative luminance 0–1 for #RRGGBB; used for booking CTA label ink. */
const hexLuminance = (hex) => {
  const h = String(hex || '').replace('#', '');
  if (!/^[0-9A-Fa-f]{6}$/.test(h)) return 0;
  const toLin = (c) => {
    const v = parseInt(c, 16) / 255;
    return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
  };
  const r = toLin(h.slice(0, 2)), g = toLin(h.slice(2, 4)), b = toLin(h.slice(4, 6));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const contrastInk = (bgHex) => (hexLuminance(bgHex) > 0.45 ? '#0f172a' : '#fff');
// Serialize appearance+logo RMWs (same idea as withDocLock).
let appearanceWriteChain = Promise.resolve();
const withAppearanceLock = (fn) => {
  const run = appearanceWriteChain.then(() => fn(), () => fn());
  appearanceWriteChain = run.catch(() => {});
  return run;
};
const defaultAppearance = () => ({
  themeId: DEFAULT_THEME_ID,
  accentOverride: '',
  assistantName: '',
  logo: null, // { ext, mime, updatedAt } when custom logo present
});
const readAppearance = () => {
  try {
    const j = JSON.parse(fs.readFileSync(APPEARANCE_FILE, 'utf8'));
    const base = defaultAppearance();
    const themeId = EMBED_THEMES[j.themeId] ? j.themeId : DEFAULT_THEME_ID;
    const accentOverride = isHexColor(j.accentOverride) ? j.accentOverride : '';
    const assistantName = typeof j.assistantName === 'string' ? j.assistantName.trim().slice(0, 60) : '';
    let logo = null;
    if (j.logo && typeof j.logo === 'object' && LOGO_EXTS.has(String(j.logo.ext || '').toLowerCase())) {
      const ext = String(j.logo.ext).toLowerCase() === 'jpeg' ? 'jpg' : String(j.logo.ext).toLowerCase();
      const file = path.join(BRAND_DIR, `logo.${ext}`);
      if (fs.existsSync(file)) {
        logo = {
          ext,
          mime: LOGO_MIME[ext] || String(j.logo.mime || ''),
          updatedAt: String(j.logo.updatedAt || ''),
        };
      }
    }
    return { ...base, themeId, accentOverride, assistantName, logo };
  } catch (e) {
    if (e.code !== 'ENOENT') console.error('[dashboard] embed-appearance.json unreadable — defaults:', e.message);
    return defaultAppearance();
  }
};
let appearanceMutex = Promise.resolve();
const writeAppearance = (app) => {
  try {
    fs.mkdirSync(STATE_DIR, { recursive: true });
    const tmp = `${APPEARANCE_FILE}.${process.pid}.tmp`;
    const payload = {
      themeId: app.themeId || DEFAULT_THEME_ID,
      accentOverride: app.accentOverride || '',
      assistantName: app.assistantName || '',
      logo: app.logo || null,
      savedAt: new Date().toISOString(),
    };
    fs.writeFileSync(tmp, JSON.stringify(payload, null, 2));
    fs.renameSync(tmp, APPEARANCE_FILE);
    return true;
  } catch (e) { console.error('[dashboard] could not persist embed appearance:', e.message); return false; }
};
const resolveTheme = (app) => {
  const t = EMBED_THEMES[app.themeId] || EMBED_THEMES[DEFAULT_THEME_ID];
  const buttonColor = isHexColor(app.accentOverride) ? app.accentOverride : t.buttonColor;
  return {
    id: t.id, name: t.name, blurb: t.blurb,
    buttonColor, userBgColor: t.userBgColor, assistantBgColor: t.assistantBgColor,
    chatIcon: CHAT_ICONS.has(t.chatIcon) ? t.chatIcon : 'chatBubble',
  };
};
const weownMarkSvg = () => (
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">' +
  '<rect x="0.5" y="0.5" width="63" height="63" rx="18" ry="18" fill="#00A3FF" ' +
  'stroke="rgba(255,255,255,0.16)" stroke-width="1"/>' +
  '<text x="32" y="34" text-anchor="middle" dominant-baseline="middle" ' +
  'font-family="system-ui,-apple-system,Segoe UI,Roboto,sans-serif" font-weight="800" ' +
  'font-size="34" fill="#ffffff" letter-spacing="-0.02em">W</text></svg>'
);
const clearCustomLogoFiles = () => {
  try {
    if (!fs.existsSync(BRAND_DIR)) return;
    for (const f of fs.readdirSync(BRAND_DIR)) {
      if (/^logo\./i.test(f)) fs.unlinkSync(path.join(BRAND_DIR, f));
    }
  } catch (e) { console.error('[dashboard] clear logo files:', e.message); }
};
const readRawBody = (req, maxBytes) => new Promise((resolve, reject) => {
  const chunks = [];
  let size = 0;
  let done = false;
  const fail = (err) => { if (done) return; done = true; try { req.destroy(); } catch {} reject(err); };
  req.on('data', (c) => {
    size += c.length;
    if (size > maxBytes) return fail(Object.assign(new Error('payload too large'), { code: 'TOO_LARGE' }));
    chunks.push(c);
  });
  req.on('end', () => { if (done) return; done = true; resolve(Buffer.concat(chunks)); });
  req.on('error', fail);
});
const logoExtFromName = (name) => {
  const m = /\.([A-Za-z0-9]+)\s*$/.exec(String(name || '').trim());
  if (!m) return '';
  const e = m[1].toLowerCase();
  return e === 'jpeg' ? 'jpg' : e;
};
const looksLikeSvg = (buf) => {
  const head = buf.slice(0, 512).toString('utf8').replace(/^\uFEFF/, '').trimStart();
  return head.startsWith('<svg') || (head.startsWith('<?xml') && /<svg[\s>]/i.test(buf.toString('utf8', 0, 2048)));
};
const svgLooksSafe = (buf) => {
  const s = buf.toString('utf8');
  // Refuse scriptable / external SVG payloads — logo is served to every visitor site.
  if (/<script[\s>]/i.test(s)) return false;
  if (/\bon\w+\s*=/i.test(s)) return false;
  if (/javascript:/i.test(s)) return false;
  if (/<foreignObject/i.test(s)) return false;
  if (/<(iframe|object|embed|style)[\s>]/i.test(s)) return false;
  if (/@import/i.test(s)) return false;
  // SMIL that can retarget event handlers
  if (/<(?:set|animate|animateTransform)[\s>][^>]*attributeName\s*=\s*["']?on\w+/i.test(s)) return false;
  // External / data / protocol-relative hrefs (fragment # refs are fine)
  if (/\b(?:xlink:)?href\s*=\s*["']?\s*(?:https?:|data:|\/\/)/i.test(s)) return false;
  return true;
};



// ── document locks ───────────────────────────────────────────────────────────
// The shared document library (see /api/documents below) is used by every
// conversation in the workspace — deleting a document doesn't just affect the
// chat you're in, it silently pulls grounding out from under every other
// conversation too. AnythingLLM has no concept of a "locked" document, so this
// is dashboard-only state (same STATE_DIR + read/write pattern as the embed
// allowlist above): a docpath in this set can't be deleted until unlocked
// again, whether or not the client-side UI agrees.
const LOCKED_FILE = path.join(STATE_DIR, 'locked-documents.json');
const readLocked = () => {
  try { return new Set(JSON.parse(fs.readFileSync(LOCKED_FILE, 'utf8')).docpaths || []); }
  catch (e) {
    // No file yet = nothing locked (normal first run). A file that EXISTS but
    // won't parse is corruption we must not hide behind a silent empty set —
    // log it loudly. The atomic write below makes crash-corruption impossible,
    // so this should never fire in practice (Copilot review, PR #141).
    if (e.code !== 'ENOENT') console.error('[dashboard] locked-documents.json unreadable — treating as empty:', e.message);
    return new Set();
  }
};
const writeLocked = (set) => {
  try {
    fs.mkdirSync(STATE_DIR, { recursive: true });
    // Atomic replace: write a temp file then rename over the target. A crash
    // mid-write can then never leave a truncated file that silently unlocks
    // EVERY document — the lock is a safety control (Copilot review, PR #141).
    const tmp = `${LOCKED_FILE}.${process.pid}.tmp`;
    fs.writeFileSync(tmp, JSON.stringify({ docpaths: [...set], savedAt: new Date().toISOString() }, null, 2));
    fs.renameSync(tmp, LOCKED_FILE);
    return true;
  } catch (e) { console.error('[dashboard] could not persist document locks:', e.message); return false; }
};

// Serialize every read-modify-write of the lock file and every
// check-then-delete, so two concurrent document operations can't clobber each
// other's lock change, nor let a just-locked document slip through a delete that
// already read the old state (Copilot review, PR #141). Single tenant, so
// contention is rare — but the lock is a safety control and must be race-free.
// Scope toggles also use this mutex for orderly embedding updates; they never purge.
let _docOpChain = Promise.resolve();
const withDocLock = (fn) => {
  const run = _docOpChain.then(fn, fn);
  _docOpChain = run.then(() => {}, () => {});
  return run;
};

// Shared docpath guard for library ops. Paths are opaque ALLM locations
// (e.g. "custom-documents/foo.json") — never absolute, never traversal.
const isValidDocpath = (docpath) => {
  const s = String(docpath || '');
  if (!s || s.length > 512) return false;
  if (s.startsWith('/') || s.includes('..') || s.includes('\0') || s.includes('\\')) return false;
  return true;
};

// Storage names look like "AI-Playbook-MEGA.pdf-<uuid>.json"; display titles
// are usually the original filename. Normalise both sides so a duplicate check
// and a preview subtitle never leak the internal …-<uuid>.json storage name.
const stripUuidJsonSuffix = (name) => String(name || '')
  .replace(/-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.json$/i, '');
const normalizeDisplayTitle = (name) => {
  const base = path.basename(String(name || '').trim());
  return stripUuidJsonSuffix(base).trim().toLowerCase();
};
const displayTitlesMatch = (a, b) => {
  const na = normalizeDisplayTitle(a);
  const nb = normalizeDisplayTitle(b);
  return !!na && !!nb && na === nb;
};
const humanTitleFromDocpath = (docpath) => {
  const base = path.basename(String(docpath || ''));
  return stripUuidJsonSuffix(base) || base || 'Document';
};

// Optional path to ALLM's storage/documents directory (the same volume the ALLM
// container writes, bind-mounted read-only into this container — see the
// dashboard service in docker/compose.prod.yaml). Mintplex
// GET /api/v1/document/:docName runs findDocumentInDocuments, which deliberately
// strips pageContent, so the API alone can never power a text preview. When this
// is set we read the stored JSON directly, ONLY under this root, with
// path-traversal guards and a hard byte cap — we never invent paths.
const ALLM_DOCUMENTS_PATH = (process.env.ALLM_DOCUMENTS_PATH || '').trim();
// Cap the on-disk read itself, before the bytes enter the heap. The preview is
// truncated to 100k chars anyway, so a JSON larger than this cap cannot improve
// the preview — it can only be an OOM lever for an authenticated caller.
const DOC_DISK_READ_MAX_BYTES = 16 * 1024 * 1024;
const isWithinDir = (root, candidate) => {
  const rel = path.relative(path.resolve(root), path.resolve(candidate));
  return rel !== '' && !rel.startsWith('..') && !path.isAbsolute(rel);
};
const readDocJsonFromDisk = (docpath) => {
  if (!ALLM_DOCUMENTS_PATH || !isValidDocpath(docpath)) return null;
  try {
    const root = path.resolve(ALLM_DOCUMENTS_PATH);
    if (!fs.existsSync(root) || !fs.statSync(root).isDirectory()) return null;
    const full = path.resolve(root, docpath);
    if (!isWithinDir(root, full)) return null;
    if (!full.toLowerCase().endsWith('.json')) return null;
    const st = fs.statSync(full);
    if (!st.isFile()) return null;
    if (st.size > DOC_DISK_READ_MAX_BYTES) {
      console.error('[dashboard] document disk read skipped: file over cap', st.size);
      return null;
    }
    const parsed = JSON.parse(fs.readFileSync(full, 'utf8'));
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch (e) {
    console.error('[dashboard] document disk read failed:', e.message);
    return null;
  }
};

// ── upload policy (locked-down release) ──────────────────────────────────────
// The uploader is the authenticated PRACTICE OWNER uploading their OWN grounding
// documents (service guide, fee schedule, Q&A sheet) — supported set is
// PDF / Markdown / plain text / CSV / Word .docx (AnythingLLM collector asDocx).
// Legacy Word 97-2003 (.doc) is refused with a convert message. End-customer
// document intake is NOT this endpoint: the public bot redirects those to the
// practice's own portal. Anything outside the allowlist is refused BEFORE a
// byte reaches AnythingLLM.
// Fleet note: if Infisical sets UPLOAD_ALLOWED_EXT, it MUST include docx (and
// any other types the UI should offer) or Word uploads will 400 at the server
// even when the browser accept= list includes them. GET /api/upload-policy
// exposes the effective list so the UI can stay honest.
const UPLOAD_ALLOWED_EXT = (process.env.UPLOAD_ALLOWED_EXT || 'pdf,md,markdown,txt,csv,docx')
  .split(',').map((s) => s.trim().toLowerCase()).filter(Boolean);
const UPLOAD_MAX_BYTES = parseInt(process.env.UPLOAD_MAX_BYTES || String(25 * 1024 * 1024), 10);
// Filename arrives in the X-Upload-Filename header (the dashboard sets it) so we can
// enforce the allowlist without parsing multipart. Belt-and-braces: the browser also
// constrains it via the file input's accept=, and the byte cap below is enforced on
// the live stream regardless of what any header claims.
const extOf = (name) => {
  const m = /\.([A-Za-z0-9]+)\s*$/.exec(String(name || '').trim());
  return m ? m[1].toLowerCase() : '';
};
const uploadRejection = (name, len) => {
  const ext = extOf(name);
  if (!name) return 'missing filename (X-Upload-Filename)';
  if (ext === 'doc') {
    return 'Word 97-2003 (.doc) isn\'t supported — save it as .docx or PDF, then upload.';
  }
  if (!ext || !UPLOAD_ALLOWED_EXT.includes(ext)) {
    return `file type ".${ext || '?'}" is not accepted — allowed: ${UPLOAD_ALLOWED_EXT.join(', ')}`;
  }
  if (len && Number(len) > UPLOAD_MAX_BYTES) {
    return `file is too large (${Math.round(Number(len) / 1048576)} MB) — limit is ${Math.round(UPLOAD_MAX_BYTES / 1048576)} MB`;
  }
  return null;
};

for (const [k, v] of Object.entries({ ALLM_ADMIN_API_KEY: API_KEY, DASHBOARD_PASSWORD_HASH: PW_HASH, DASHBOARD_SESSION_SECRET: SESSION_SECRET })) {
  if (!v) { console.error(`refusing to start: ${k} not injected — set it in Infisical`); process.exit(1); }
}

// ── OIDC login (Keycloak `weown-chat` realm) ─────────────────────────────────
// Provisioned per tenant by weown-fleet/scripts/kc-provision-tenant.sh, which
// stores OIDC_ISSUER / OIDC_CLIENT_ID / OIDC_CLIENT_SECRET / OIDC_ALLOWED_GROUP
// in the tenant's Infisical folder — when they're present the login page offers
// "Sign in with WeOwn" (authorization-code flow, server-side exchange; the
// browser never sees tokens). Authorization = membership of the tenant group in
// the userinfo `groups` claim. The password login stays as break-glass.
// Zero-dependency: plain https + the same HMAC session cookie as passwords.
const OIDC = {
  issuer: (process.env.OIDC_ISSUER || '').replace(/\/$/, ''),
  clientId: process.env.OIDC_CLIENT_ID || '',
  clientSecret: process.env.OIDC_CLIENT_SECRET || '',
  group: process.env.OIDC_ALLOWED_GROUP || '',
};
const oidcEnabled = () => !!(OIDC.issuer && OIDC.clientId && OIDC.clientSecret && OIDC.group);

// ── entitlement ──────────────────────────────────────────────────────────────
// Deny ONLY on an explicit false. This asymmetry is deliberate and load-bearing:
// the claim is absent for every user whose client has no mapper yet, and for
// every user billing has never touched. Failing closed on an absent claim would
// lock out the entire existing fleet the moment this deploys — turning an
// entitlement feature into an outage. Absent means "billing has said nothing",
// which is not the same as "not entitled".
//
// The consequence, stated plainly so nobody assumes more than is true: this gate
// is exactly as good as billing's writes. If the attribute never lands on the
// user, nothing is enforced. The write path (billing keycloak.set_subscription_active)
// and the claim mapper (weown-fleet kc-provision-tenant.sh) are both required.
//
// Keycloak renders a single-valued user attribute as a bare string, but a
// multivalued one arrives as an array, and a JSON-typed mapper can yield a real
// boolean — accept all three rather than trusting one shape.
const entitlementDenied = (claims) => {
  if (!claims || !('subscription_active' in claims)) return false; // absent → allow
  let v = claims.subscription_active;
  if (Array.isArray(v)) v = v[0];
  if (v === false) return true;
  return String(v).trim().toLowerCase() === 'false';
};
const oidcRedirectUri = () => `https://${PUBLIC_DOMAIN}${BASE}/oidc/callback`;
const libFor = (u) => (u.protocol === 'https:' ? https : http);
const postForm = (urlStr, form) => new Promise((resolve, reject) => {
  const u = new URL(urlStr);
  const body = new URLSearchParams(form).toString();
  const req = libFor(u).request(u, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': Buffer.byteLength(body) } }, (res) => {
    let d = ''; res.on('data', (c) => (d += c));
    res.on('end', () => { try { resolve({ status: res.statusCode, json: JSON.parse(d) }); } catch { resolve({ status: res.statusCode, json: null }); } });
  });
  req.on('error', reject); req.setTimeout(30e3, () => req.destroy(new Error('OIDC request timeout')));
  req.end(body);
});
const getJson = (urlStr, bearer) => new Promise((resolve, reject) => {
  const u = new URL(urlStr);
  const req = libFor(u).request(u, { method: 'GET', headers: { Authorization: `Bearer ${bearer}` } }, (res) => {
    let d = ''; res.on('data', (c) => (d += c));
    res.on('end', () => { try { resolve({ status: res.statusCode, json: JSON.parse(d) }); } catch { resolve({ status: res.statusCode, json: null }); } });
  });
  req.on('error', reject); req.setTimeout(30e3, () => req.destroy(new Error('OIDC request timeout')));
  req.end();
});

// ── sessions: HMAC-signed expiry cookie, SameSite=Strict ─────────────────────
const hmac = (s) => crypto.createHmac('sha256', SESSION_SECRET).update(s).digest('hex');
const makeSession = () => { const exp = Date.now() + 12 * 3600e3; return `${exp}.${hmac(String(exp))}`; };
const validSession = (c) => {
  const m = /(?:^|;\s*)dsession=([^;]+)/.exec(c || ''); if (!m) return false;
  const [exp, sig] = m[1].split('.'); if (!exp || !sig) return false;
  try {
    return Number(exp) > Date.now() &&
      crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(hmac(exp)));
  } catch { return false; }
};

// naive login rate limit: 10 attempts / 10 min per IP
const attempts = new Map();
const throttled = (ip) => {
  const now = Date.now();
  const a = (attempts.get(ip) || []).filter((t) => now - t < 600e3);
  attempts.set(ip, a);
  return a.length >= 10;
};

// ── ALLM proxy helper ────────────────────────────────────────────────────────
function allm(method, apiPath, { body, headers, stream } = {}) {
  return new Promise((resolve, reject) => {
    const u = new URL(apiPath, ALLM_URL);
    const lib = u.protocol === 'https:' ? https : http;
    const req = lib.request(u, { method, headers: { Authorization: `Bearer ${API_KEY}`, Accept: 'application/json', ...headers } }, (res) => {
      let data = '';
      res.on('data', (c) => (data += c));
      res.on('end', () => {
        let json = null; try { json = JSON.parse(data); } catch { /* non-JSON */ }
        resolve({ status: res.statusCode, json, raw: data });
      });
    });
    req.on('error', reject);
    req.setTimeout(240e3, () => req.destroy(new Error('ALLM request timeout')));
    if (stream) stream.pipe(req);
    else { if (body !== undefined) req.end(JSON.stringify(body)); else req.end(); }
  });
}

const send = (res, code, obj, extra = {}) => {
  const body = typeof obj === 'string' ? obj : JSON.stringify(obj);
  res.writeHead(code, { 'Content-Type': typeof obj === 'string' ? 'text/html; charset=utf-8' : 'application/json', 'Cache-Control': 'no-store', ...extra });
  res.end(body);
};
const page = (name) => fs.readFileSync(path.join(__dirname, 'public', name), 'utf8');
// Reasoning models (DeepSeek/Kimi) emit <think>…</think> blocks that AnythingLLM
// passes through verbatim — customers must never see the model's internal
// reasoning (it narrates their documents back at them). Strip everywhere chat
// text leaves this server: live replies and stored history.
const stripThink = (t) => String(t || '').replace(/<think>[\s\S]*?<\/think>/gi, '').trim();

// Default 256 KiB for tiny JSON (docpath + flags). /api/chat may carry
// base64 chat attachments — use readBody(req, CHAT_BODY_MAX_BYTES) there.
const READ_BODY_DEFAULT_MAX = 262144;
const parsePositiveInt = (raw, fallback) => {
  const n = parseInt(raw, 10);
  return Number.isFinite(n) && n > 0 ? n : fallback;
};
const CHAT_ATTACH_MAX = 3;
const CHAT_ATTACH_MAX_B64 = parsePositiveInt(process.env.CHAT_ATTACH_MAX_B64, 4 * 1024 * 1024); // ~3 MiB raw
// The body cap must be able to CARRY a full attachment set, or the limits
// contradict each other: readBody destroys the socket, the client's fetch
// rejects, and the customer is told "could not reach the server" for two
// ordinary PDFs. Derive it from the attachment budget so the two cannot drift
// apart again; an explicit env value still wins, but never below the budget.
const CHAT_BODY_FLOOR = CHAT_ATTACH_MAX * CHAT_ATTACH_MAX_B64 + 512 * 1024; // + room for text/JSON overhead
const CHAT_BODY_MAX_BYTES = Math.max(
  parsePositiveInt(process.env.CHAT_BODY_MAX_BYTES, 6 * 1024 * 1024),
  CHAT_BODY_FLOOR,
);
const CHAT_ATTACH_DATA_MIMES = new Set([
  'application/pdf', 'text/plain', 'text/csv', 'text/markdown', 'text/x-markdown',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
]);
const readBody = (req, maxBytes = READ_BODY_DEFAULT_MAX) => new Promise((r) => {
  // Cap the buffer so an authenticated client can't grow the process heap with
  // a huge body; over the cap we stop reading and resolve empty, which the
  // handlers' own validation then rejects as a 400 (Copilot review, PR #141).
  // destroy() may only emit 'close' (not 'error'/'end') — always settle.
  let d = '', len = 0, over = false, settled = false;
  const done = (val) => { if (settled) return; settled = true; r(val); };
  req.on('data', (c) => {
    len += c.length; if (over) return;
    if (len > maxBytes) { over = true; d = ''; req.destroy(); return; }
    d += c;
  });
  req.on('end', () => { try { done(JSON.parse(d || '{}')); } catch { done({}); } });
  req.on('error', () => done({}));
  req.on('close', () => { if (over || !settled) done({}); });
});
// Sanitize ALLM chat attachments (Mintplex #4797): non-image docs MUST use
// mime application/anythingllm-document + a data:…;base64,… contentString.
// We never invent attachments — only forward allowlisted client payloads.
const sanitizeChatAttachments = (raw) => {
  if (raw == null) return { ok: true, attachments: undefined };
  if (!Array.isArray(raw)) return { ok: false, error: 'attachments must be an array' };
  if (raw.length > CHAT_ATTACH_MAX) return { ok: false, error: `at most ${CHAT_ATTACH_MAX} attachments per message` };
  const out = [];
  for (const a of raw) {
    if (!a || typeof a !== 'object') return { ok: false, error: 'invalid attachment' };
    const name = String(a.name || '').trim();
    const mime = String(a.mime || '').trim();
    const contentString = String(a.contentString || '');
    const reject = uploadRejection(name, null);
    if (reject) return { ok: false, error: reject };
    if (mime !== 'application/anythingllm-document') {
      return { ok: false, error: 'attachment mime must be application/anythingllm-document' };
    }
    const m = /^data:([^;,]+);base64,([A-Za-z0-9+/=\s]+)$/.exec(contentString);
    if (!m) {
      return { ok: false, error: 'attachment contentString must be a data:…;base64,… URI' };
    }
    const dataMime = m[1].trim().toLowerCase();
    if (!CHAT_ATTACH_DATA_MIMES.has(dataMime)) {
      return { ok: false, error: `attachment data type "${dataMime}" is not accepted` };
    }
    const b64 = m[2].replace(/\s+/g, '');
    if (!b64 || b64.length > CHAT_ATTACH_MAX_B64) {
      return { ok: false, error: `attachment "${name}" is too large` };
    }
    // Re-normalize so upstream always gets a clean data URI.
    out.push({ name, mime, contentString: `data:${dataMime};base64,${b64}` });
  }
  return { ok: true, attachments: out.length ? out : undefined };
};

// Health means "a customer can use this", not "this process is alive". Every
// dashboard action goes to AnythingLLM, so with the app down the dashboard is a
// green door onto a dead room: it renders, logs in, and then fails on every
// click — which testers report as "it's up but broken", feedback about our
// health display rather than the product (acceptance drill, 2026-09-01: app in
// a deliberate outage, dashboard healthy and serving /app/ 200 throughout).
// Probe the app's own liveness; 503 when it is unreachable. Unauthenticated
// and cheap (no API key, 3s cap) — compose's healthcheck and the public probe
// both hit this.
function healthz(res) {
  const u = new URL('/api/ping', ALLM_URL);
  const req = (u.protocol === 'https:' ? https : http).get(u, (r) => {
    r.resume();
    if (r.statusCode === 200) return send(res, 200, { ok: true, app: 'online' });
    send(res, 503, { ok: false, app: `status ${r.statusCode}` });
  });
  req.setTimeout(3000, () => req.destroy(new Error('timeout')));
  req.on('error', (e) => send(res, 503, { ok: false, app: e.message }));
}

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, 'http://x');
    let p = url.pathname;
    if (p === '/healthz') return healthz(res);
    if (!p.startsWith(BASE)) return send(res, 302, 'redirecting', { Location: BASE + '/' });
    p = p.slice(BASE.length) || '/';
    // Public health probe. Caddy only routes /app* here, so `/healthz` above is
    // unreachable from outside the compose network — a deploy check against the
    // public URL has to be able to hit BASE + /healthz, before any auth.
    if (p === '/healthz') return healthz(res);
    const authed = validSession(req.headers.cookie);

    // CSRF: all state-changing calls must carry the custom header (fetch-only)
    if (req.method !== 'GET' && req.headers['x-dashboard'] !== '1' && p !== '/api/login')
      return send(res, 403, { error: 'missing X-Dashboard header' });

    // ── auth ──
    if (p === '/api/login' && req.method === 'POST') {
      const ip = req.socket.remoteAddress || '?';
      if (throttled(ip)) return send(res, 429, { error: 'too many attempts — wait 10 minutes' });
      const { email, password } = await readBody(req);
      const ok = verifyPassword(password) &&
                 (!CUSTOMER_EMAIL || (email || '').toLowerCase() === CUSTOMER_EMAIL);
      if (!ok) { attempts.get(ip).push(Date.now()); return send(res, 401, { error: 'invalid credentials' }); }
      return send(res, 200, { ok: true }, { 'Set-Cookie': `dsession=${makeSession()}; Path=${BASE}; HttpOnly; SameSite=Strict; Secure; Max-Age=43200` });
    }
    if (p === '/api/logout' && req.method === 'POST')
      return send(res, 200, { ok: true }, { 'Set-Cookie': `dsession=x; Path=${BASE}; HttpOnly; SameSite=Strict; Secure; Max-Age=0` });

    // ── OIDC (GET-only flow; state is HMAC-signed so no server-side session) ──
    if (p === '/api/authcfg' && req.method === 'GET')
      return send(res, 200, { oidc: oidcEnabled() });
    if (p === '/oidc/login' && req.method === 'GET') {
      if (!oidcEnabled()) return send(res, 404, { error: 'SSO not configured' });
      const st = `${Date.now()}.${crypto.randomBytes(8).toString('hex')}`;
      const state = `${st}.${hmac(`oidc:${st}`)}`;
      const auth = `${OIDC.issuer}/protocol/openid-connect/auth?` + new URLSearchParams({
        client_id: OIDC.clientId, redirect_uri: oidcRedirectUri(),
        response_type: 'code', scope: 'openid email', state,
      }).toString();
      return send(res, 302, 'redirecting', { Location: auth });
    }
    if (p === '/oidc/callback' && req.method === 'GET') {
      if (!oidcEnabled()) return send(res, 404, { error: 'SSO not configured' });
      const code = url.searchParams.get('code') || '';
      const state = url.searchParams.get('state') || '';
      const m = /^(\d+)\.([0-9a-f]+)\.([0-9a-f]+)$/.exec(state);
      const stateOk = !!m && Number(m[1]) > Date.now() - 600e3 && (() => {
        try { return crypto.timingSafeEqual(Buffer.from(m[3]), Buffer.from(hmac(`oidc:${m[1]}.${m[2]}`))); } catch { return false; }
      })();
      if (!code || !stateOk) return send(res, 400, { error: 'invalid SSO state — start again at ' + BASE + '/' });
      const tok = await postForm(`${OIDC.issuer}/protocol/openid-connect/token`, {
        grant_type: 'authorization_code', code, redirect_uri: oidcRedirectUri(),
        client_id: OIDC.clientId, client_secret: OIDC.clientSecret,
      });
      const access = tok.json && tok.json.access_token;
      if (tok.status !== 200 || !access) { console.error('[dashboard] OIDC token exchange failed:', tok.status); return send(res, 401, { error: 'SSO sign-in failed' }); }
      // userinfo comes from the issuer over TLS — no local JWT verification
      // needed, the source of truth is asked directly.
      const ui = await getJson(`${OIDC.issuer}/protocol/openid-connect/userinfo`, access);
      const groups = (ui.json && ui.json.groups) || [];
      if (ui.status !== 200 || !Array.isArray(groups) || !groups.includes(OIDC.group)) {
        console.error('[dashboard] OIDC login rejected: not in', OIDC.group);
        return send(res, 403, { error: 'this account is not authorized for this dashboard — ask WeOwn support to add you' });
      }
      // Entitlement. Billing writes `subscription_active` onto the Keycloak user
      // when a subscription starts, lapses or is cancelled; a claim mapper on the
      // tenant client puts it in userinfo. Until 2026-08-16 nothing read it, so a
      // cancelled customer kept a fully working instance.
      if (entitlementDenied(ui.json)) {
        console.warn('[dashboard] OIDC login blocked: subscription_active=false');
        return send(res, 402, {
          error: 'This subscription is not active. Reactivate it in billing and sign in again — '
               + 'your documents and workspaces are untouched.',
        });
      }
      return send(res, 302, 'redirecting', {
        Location: BASE + '/',
        'Set-Cookie': `dsession=${makeSession()}; Path=${BASE}; HttpOnly; SameSite=Lax; Secure; Max-Age=43200`,
      });
    }

    // ── pages ──
    if (p === '/' || p === '') return send(res, 200, page(authed ? 'index.html' : 'login.html'));
    if (p === '/version') return send(res, 200, { version: VERSION });

    // Public brand assets for the embed widget (Mintplex data-brand-image-url).
    // Unauthenticated on purpose: customer websites load these cross-origin with
    // no dashboard session. Paths are under BASE (p already stripped).
    if (p === '/brand/weownchat-mark.svg' && req.method === 'GET') {
      return send(res, 200, weownMarkSvg(), {
        'Content-Type': 'image/svg+xml; charset=utf-8',
        'Cache-Control': 'public, max-age=86400',
        'Access-Control-Allow-Origin': '*',
      });
    }
    if (p === '/brand/logo' && req.method === 'GET') {
      const app = readAppearance();
      if (app.logo && app.logo.ext) {
        const file = path.join(BRAND_DIR, `logo.${app.logo.ext}`);
        try {
          if (fs.existsSync(file)) {
            const buf = fs.readFileSync(file);
            res.writeHead(200, {
              'Content-Type': app.logo.mime || LOGO_MIME[app.logo.ext] || 'application/octet-stream',
              'Content-Length': buf.length,
              'Cache-Control': 'public, max-age=3600',
              'Access-Control-Allow-Origin': '*',
            });
            return res.end(buf);
          }
        } catch (e) { console.error('[dashboard] brand logo read:', e.message); }
      }
      // No custom logo — fall back to the WeOwn mark so /brand/logo always resolves.
      return send(res, 200, weownMarkSvg(), {
        'Content-Type': 'image/svg+xml; charset=utf-8',
        'Cache-Control': 'public, max-age=300',
        'Access-Control-Allow-Origin': '*',
      });
    }

    if (!authed) return send(res, 401, { error: 'not authenticated' });

    // ── identity (sidebar display only — not a secret, just never shown to
    // the client until now; DASHBOARD_CUSTOMER_EMAIL is optional, so this
    // may come back null on instances that don't set it) ──
    if (p === '/api/whoami' && req.method === 'GET')
      return send(res, 200, { email: CUSTOMER_EMAIL || null, billingUrl: BILLING_URL || null });

    // ── documents: one shared library, not two separate uploads. A document
    // is independently on/off for each workspace (adds/deletes via
    // update-embeddings). The library is the union of what's embedded in
    // WS.private and WS.public PLUS any system-store files not currently
    // scoped to either (so operators can re-toggle scopes after turning both
    // off). Turning a scope off only detaches embeddings — it never purges
    // the file. Explicit purge lives only on POST /api/documents/delete.
    // Reuses ALLM workspace GET, update-embeddings, system documents list,
    // and (delete only) remove-documents. ──
    const docsOf = async (scope) => {
      const r = await allm('GET', `/api/v1/workspace/${WS[scope]}`);
      // Verified against a live ALLM (2026-08-05): GET /api/v1/workspace/<slug>
      // returns { workspace: [ { ..., documents: [] } ] } — `workspace` is an
      // ARRAY, and even an EMPTY workspace includes `documents: []`. So a 200
      // that does NOT yield a documents array is an UNEXPECTED shape, never a
      // legitimate "no documents". Return ok:false there so callers that need
      // to know whether the other workspace still has a doc (e.g. UI messaging)
      // fail loud instead of guessing (Copilot review, PR #141).
      const wsList = (r.json || {}).workspace;
      const ws = Array.isArray(wsList) ? wsList[0] : wsList;
      const docs = ws && Array.isArray(ws.documents) ? ws.documents : null;
      return { ok: r.status === 200 && docs !== null, docs: docs || [] };
    };
    // Flat view of the library — the same private + public + system-store union
    // GET /api/documents builds, reduced to what the replace-on-upload path
    // needs: { path, name, locked }. Kept beside docsOf so both handlers share
    // one source of truth for "what is in the library".
    const mergedLibrary = async () => {
      const [priv, pub] = await Promise.all([docsOf('private'), docsOf('public')]);
      const locked = readLocked();
      const nameOf = (d) => {
        if (!d.metadata) return humanTitleFromDocpath(d.docpath);
        try { return JSON.parse(d.metadata).title || humanTitleFromDocpath(d.docpath); }
        catch { return humanTitleFromDocpath(d.docpath); }
      };
      const byPath = new Map();
      const add = (dp, nm) => { if (dp && !byPath.has(dp)) byPath.set(dp, { path: dp, name: nm, locked: locked.has(dp) }); };
      priv.docs.forEach((d) => add(d.docpath, nameOf(d)));
      pub.docs.forEach((d) => add(d.docpath, nameOf(d)));
      try {
        const sys = await allm('GET', '/api/v1/documents');
        const root = sys.json && sys.json.localFiles;
        const flatten = (items, parentFolder) => {
          if (!Array.isArray(items)) return;
          for (const item of items) {
            if (!item) continue;
            if (item.type === 'folder' || Array.isArray(item.items)) {
              const folderName = item.name
                ? (parentFolder ? `${parentFolder}/${item.name}` : item.name)
                : parentFolder || '';
              flatten(item.items || [], folderName);
              continue;
            }
            const fn = item.name || item.title || '';
            if (!fn || fn.includes('..') || fn.includes('/') || fn.includes('\\')) continue;
            const dp = parentFolder ? `${parentFolder}/${fn}` : fn;
            if (!isValidDocpath(dp)) continue;
            let title = item.title || fn;
            if (item.metadata) {
              try {
                const meta = typeof item.metadata === 'string' ? JSON.parse(item.metadata) : item.metadata;
                if (meta && meta.title) title = meta.title;
              } catch { /* keep title */ }
            }
            add(dp, title);
          }
        };
        if (sys.status === 200 && root) flatten(root.items || [], '');
      } catch (e) {
        console.error('[dashboard] merged library: system documents list error:', e.message);
      }
      return [...byPath.values()];
    };
    if (p === '/api/documents' && req.method === 'GET') {
      const [priv, pub] = await Promise.all([docsOf('private'), docsOf('public')]);
      if (!priv.ok && !pub.ok) return send(res, 502, { error: 'could not load documents' });
      // metadata is ALLM-controlled JSON text, not something this server
      // writes — a malformed/legacy blob must fall back to the docpath, not
      // 500 the whole /api/documents response (Copilot review, PR #141).
      const nameOf = (d) => {
        if (!d.metadata) return d.docpath;
        try { return JSON.parse(d.metadata).title || d.docpath; }
        catch { return d.docpath; }
      };
      const locked = readLocked();
      const byPath = new Map();
      priv.docs.forEach((d) => byPath.set(d.docpath, { id: d.id, path: d.docpath, name: nameOf(d), private: true, public: false, locked: locked.has(d.docpath) }));
      pub.docs.forEach((d) => {
        const existing = byPath.get(d.docpath);
        if (existing) existing.public = true;
        else byPath.set(d.docpath, { id: d.id, path: d.docpath, name: nameOf(d), private: false, public: true, locked: locked.has(d.docpath) });
      });
      // Also surface system-store files that aren't embedded in either
      // workspace (private:false, public:false) so turning both scopes off
      // never hides a document from the library — operators can re-toggle.
      // Failure here must not 502 the whole list (workspace docs still useful).
      try {
        const sys = await allm('GET', '/api/v1/documents');
        const root = sys.json && sys.json.localFiles;
        const flatten = (items, parentFolder) => {
          if (!Array.isArray(items)) return;
          for (const item of items) {
            if (!item) continue;
            const isFolder = item.type === 'folder' || Array.isArray(item.items);
            if (isFolder) {
              // Append — do not replace — or nested paths collapse and miss
              // workspace docpath matches (custom-documents/harbor/qa.json).
              const folderName = item.name
                ? (parentFolder ? `${parentFolder}/${item.name}` : item.name)
                : parentFolder || '';
              flatten(item.items || [], folderName);
              continue;
            }
            // File items: workspace docs use docpath like "custom-documents/foo.json"
            const fname = item.name || item.title || '';
            if (!fname || fname.includes('..') || fname.includes('/') || fname.includes('\\')) continue;
            const docpath = parentFolder ? `${parentFolder}/${fname}` : fname;
            if (!isValidDocpath(docpath)) continue;
            if (byPath.has(docpath)) continue;
            let title = item.title || fname;
            if (item.metadata) {
              try {
                const meta = typeof item.metadata === 'string' ? JSON.parse(item.metadata) : item.metadata;
                if (meta && meta.title) title = meta.title;
              } catch { /* keep title */ }
            }
            byPath.set(docpath, {
              id: item.id || docpath,
              path: docpath,
              name: title,
              private: false,
              public: false,
              locked: locked.has(docpath),
            });
          }
        };
        if (sys.status === 200 && root) flatten(root.items || [], '');
        else if (sys.status !== 200) console.error('[dashboard] system documents list failed:', sys.status);
      } catch (e) {
        console.error('[dashboard] system documents list error:', e.message);
      }
      return send(res, 200, { documents: [...byPath.values()] });
    }

    if (p === '/api/upload-policy' && req.method === 'GET') {
      // Effective allowlist (env UPLOAD_ALLOWED_EXT overrides the default).
      // UI should mirror this so fleet Infisical overrides do not lie to users.
      return send(res, 200, {
        allowedExt: UPLOAD_ALLOWED_EXT.slice(),
        maxBytes: UPLOAD_MAX_BYTES,
        legacyDocHint: 'Word 97-2003 (.doc) isn\'t supported — save it as .docx or PDF, then upload.',
      });
    }

    if (p === '/api/documents/content' && req.method === 'GET') {
      const docpath = (url.searchParams.get('path') || '').trim();
      if (!docpath) return send(res, 400, { error: 'path required' });
      if (!isValidDocpath(docpath)) return send(res, 400, { error: 'invalid path' });
      // ALLM GET /v1/document/:docName looks up by filename inside each storage
      // folder (not by full "folder/file" location). Full docpaths 404; basename
      // can hit the wrong folder when two files share a name. Fetch by basename,
      // then require metadata.location (when present) to match the requested path.
      const tryFetch = async (name) => allm('GET', `/api/v1/document/${encodeURIComponent(name)}`);
      const base = path.basename(docpath);
      let r = await tryFetch(base || docpath);
      if (r.status === 404) return send(res, 404, { error: 'document not found' });
      if (r.status !== 200 || !r.json) {
        console.error('[dashboard] document content failed:', r.status, (r.json && r.json.error) || '');
        return send(res, 502, { error: 'could not load document content' });
      }
      const j = r.json;
      // ALLM shapes vary: sometimes { pageContent, title, name }, sometimes nested under document
      const doc = j.document || j;
      const norm = (s) => String(s || '').trim().replace(/^\/+/, '');
      const loc = norm(doc.location || doc.docpath || '');
      const reqPath = norm(docpath);
      // Only hard-fail when ALLM returns a folder-qualified location that
      // disagrees with the requested path. A bare filename (or missing
      // location) cannot prove the folder — do not 409 on that, or normal
      // previews of custom-documents/file.json break when location is basename-only.
      if (loc.includes('/') && loc !== reqPath) {
        // Folders only — document filenames are customer content, and on hosts
        // running the fleet log agent these lines leave the box unredacted.
        const dirOf = (x) => { const i = String(x).lastIndexOf('/'); return i < 0 ? '(root)' : String(x).slice(0, i); };
        console.error('[dashboard] document content location mismatch:', { requestedDir: dirOf(reqPath), gotDir: dirOf(loc) });
        return send(res, 409, {
          error: 'Another document shares this file name in a different folder — rename one, then open it again.',
        });
      }
      let pageContent = doc.pageContent || doc.text || doc.content || '';
      if (typeof pageContent !== 'string') pageContent = String(pageContent || '');
      // Mintplex strips pageContent from the document API response, so for most
      // real files the block above yields ''. Fall back to the stored JSON on
      // the shared volume when ALLM_DOCUMENTS_PATH is configured.
      let disk = null;
      if (!pageContent) {
        disk = readDocJsonFromDisk(docpath);
        if (disk) {
          const fromDisk = disk.pageContent || disk.text || disk.content || '';
          pageContent = typeof fromDisk === 'string' ? fromDisk : String(fromDisk || '');
        }
      }
      const MAX = 100000;
      if (pageContent.length > MAX) pageContent = pageContent.slice(0, MAX) + '\n\n… [truncated]';
      // Never surface the internal …-<uuid>.json storage basename — prefer the
      // stored title, then ALLM's title, then a de-suffixed filename.
      const title = (disk && disk.title) || doc.title || humanTitleFromDocpath(docpath);
      const name = title;
      // When there is still no text, tell the client WHY so it can show an
      // honest note instead of an alarming "could not load" error: an
      // unconfigured instance is an ops gap, not a per-document failure.
      const previewUnavailable = pageContent ? null
        : (ALLM_DOCUMENTS_PATH ? 'no-extracted-text' : 'not-configured');
      // Report the location ALLM actually gave us. Echoing the REQUESTED path
      // when ALLM returned none would assert a match we never made — and the
      // client uses this to decide what it is looking at.
      return send(res, 200, { name, title, pageContent, previewUnavailable, location: loc || null, locationVerified: !!loc });
    }
    if (p === '/api/documents/lock' && req.method === 'POST') {
      const { docpath, locked: wantLocked } = await readBody(req);
      if (!docpath) return send(res, 400, { error: 'docpath required' });
      if (!isValidDocpath(docpath)) return send(res, 400, { error: 'invalid path' });
      // Same boolean discipline as /api/documents/scope's `on` — a malformed
      // `locked` must not be coerced into an accidental unlock (or, e.g., a
      // truthy string like "false" into an accidental lock)
      // (Copilot review, PR #141).
      if (typeof wantLocked !== 'boolean') return send(res, 400, { error: 'locked must be true or false' });
      // Read-modify-write under the mutex so a concurrent lock/unlock or a
      // purge can't clobber this change (Copilot review, PR #141).
      const saved = await withDocLock(async () => {
        const set = readLocked();
        if (wantLocked) set.add(docpath); else set.delete(docpath);
        // writeLocked()'s return value was previously ignored, so a failed
        // write (disk full, permissions) still reported {ok:true} — the client
        // would believe the lock took even though it evaporates on next read
        // (Copilot review, PR #141).
        return writeLocked(set);
      });
      if (!saved) return send(res, 502, { error: 'could not save the lock — try again' });
      return send(res, 200, { ok: true, locked: wantLocked });
    }
    if (p === '/api/upload' && req.method === 'POST') {
      // Locked-down upload policy: refuse disallowed types / oversized files BEFORE
      // any byte reaches AnythingLLM.
      const fname = req.headers['x-upload-filename'] || '';
      const scope = req.headers['x-upload-scope'] === 'public' ? 'public' : 'private';
      const onDup = String(req.headers['x-upload-on-duplicate'] || 'keep').trim().toLowerCase() === 'replace'
        ? 'replace' : 'keep';
      const reject = uploadRejection(fname, req.headers['content-length']);
      if (reject) {
        req.resume(); // drain so the client gets the response instead of a reset
        return send(res, 400, { error: reject });
      }
      // Replace-on-duplicate is UPLOAD → VERIFY → DELETE, never delete-first:
      // the customer must never be left with nothing because a fresh upload
      // failed after the old copy was already gone. The only work done here,
      // before the upload, is a locked-doc pre-check — so a doomed replace
      // fails fast instead of wasting the transfer. The client sends only the
      // header; it does NOT pre-delete (that would double the destructive work).
      let replaceTargets = [];
      if (onDup === 'replace') {
        const lib = await mergedLibrary();
        replaceTargets = lib.filter((d) => displayTitlesMatch(fname, d.name) || displayTitlesMatch(fname, d.path));
        const lockedHit = replaceTargets.find((d) => d.locked);
        if (lockedHit) {
          req.resume();
          return send(res, 409, { error: `Unlock ${lockedHit.name} first` });
        }
      }
      // Enforce the byte cap on the live stream too — content-length may be absent
      // or untrue; this kills the transfer the moment it exceeds the limit.
      let seen = 0, aborted = false;
      req.on('data', (c) => {
        seen += c.length;
        if (seen > UPLOAD_MAX_BYTES && !aborted) {
          aborted = true;
          req.destroy(new Error('upload exceeded size limit'));
        }
      });
      // stream the multipart body through to ALLM (never parsed here)
      const up = await allm('POST', '/api/v1/document/upload', { headers: { 'content-type': req.headers['content-type'], 'content-length': req.headers['content-length'] }, stream: req });
      if (aborted) return send(res, 413, { error: `file exceeded the ${Math.round(UPLOAD_MAX_BYTES / 1048576)} MB limit` });
      const loc = up.json && up.json.documents && up.json.documents[0] && up.json.documents[0].location;
      if (!loc) return send(res, 502, { error: 'upload failed', detail: (up.json && up.json.error) || up.status });
      const emb = await allm('POST', `/api/v1/workspace/${WS[scope]}/update-embeddings`, { body: { adds: [loc] }, headers: { 'content-type': 'application/json' } });
      if (emb.status !== 200) return send(res, 502, { error: 'uploaded but embedding failed', detail: (emb.json && emb.json.error) || emb.status });
      // New file is up and embedded — NOW retire the old copies. A failure here
      // is reported, never swallowed: the new document already replaced the old
      // in every practical sense, so this is a warning on a 200, not a 5xx, but
      // the customer is told exactly what was left behind.
      let replaced = 0;
      const replaceWarnings = [];
      if (onDup === 'replace') {
        const dirOf = (x) => { const i = String(x).lastIndexOf('/'); return i < 0 ? '(root)' : String(x).slice(0, i); };
        for (const m of replaceTargets) {
          if (m.path === loc) continue; // never delete the file we just wrote
          const out = await withDocLock(async () => {
            if (readLocked().has(m.path)) return { warn: `"${m.name}" was locked mid-upload — the old copy was kept` };
            const detaches = await Promise.all(['private', 'public'].map((s) =>
              allm('POST', `/api/v1/workspace/${WS[s]}/update-embeddings`, { body: { deletes: [m.path] }, headers: { 'content-type': 'application/json' } })
            ));
            if (detaches.some((d) => d.status !== 200)) {
              console.error('[dashboard] replace-delete detach failed in', dirOf(m.path));
              return { warn: `could not fully detach the previous "${m.name}" — it may still be embedded in one chat` };
            }
            const rm = await allm('DELETE', '/api/v1/system/remove-documents', { body: { names: [m.path] }, headers: { 'content-type': 'application/json' } });
            if (rm.status !== 200) {
              console.error('[dashboard] replace-delete remove-documents failed:', rm.status, 'in', dirOf(m.path));
              return { warn: `removed the previous "${m.name}" from every chat, but it is still in storage` };
            }
            const s = readLocked(); if (s.delete(m.path)) writeLocked(s);
            return { ok: true };
          });
          if (out && out.ok) replaced += 1;
          else if (out && out.warn) replaceWarnings.push(out.warn);
        }
      }
      return send(res, 200, { ok: true, location: loc, scope, replaced, replaceWarnings });
    }
    if (p === '/api/documents/scope' && req.method === 'POST') {
      const { docpath, scope, on } = await readBody(req);
      if (!docpath || (scope !== 'private' && scope !== 'public')) return send(res, 400, { error: 'docpath and scope required' });
      if (!isValidDocpath(docpath)) return send(res, 400, { error: 'invalid path' });
      // A missing/malformed `on` must not be silently treated as "off" and
      // detach a document nobody asked to detach (Copilot review, PR #141).
      if (typeof on !== 'boolean') return send(res, 400, { error: 'on must be true or false' });
      // Scope toggles only add/remove embeddings for this workspace. Turning
      // the last scope off leaves the file in ALLM's system store (still listed
      // by GET /api/documents via the system documents merge). Hard-delete /
      // purge is ONLY on POST /api/documents/delete — never here. Lock does
      // not gate scope toggles (lock only blocks delete).
      const out = await withDocLock(async () => {
        const op = on ? 'adds' : 'deletes';
        const emb = await allm('POST', `/api/v1/workspace/${WS[scope]}/update-embeddings`, { body: { [op]: [docpath] }, headers: { 'content-type': 'application/json' } });
        if (emb.status !== 200) {
          // Log the upstream detail server-side; don't echo raw ALLM internals
          // back to the client (Copilot review, PR #141).
          console.error('[dashboard] scope update failed:', scope, emb.status, (emb.json && emb.json.error) || '');
          return { code: 502, body: { error: `could not update ${scope}` } };
        }
        return { code: 200, body: { ok: true } };
      });
      return send(res, out.code, out.body);
    }
    if (p === '/api/documents/delete' && req.method === 'POST') {
      const { docpath } = await readBody(req);
      if (!docpath) return send(res, 400, { error: 'docpath required' });
      if (!isValidDocpath(docpath)) return send(res, 400, { error: 'invalid path' });
      // Server-side is the real gate, not just the disabled button — the same
      // invariant as every other guard in this file (CSRF header, upload
      // allowlist, non-emptyable allowed-websites list).
      // Lock check → detach → purge runs under the mutex so a concurrent lock
      // can't land between the check and the purge (Copilot review, PR #141).
      const out = await withDocLock(async () => {
        if (readLocked().has(docpath)) return { code: 409, body: { error: 'this document is locked — unlock it first, then delete' } };
        const detaches = await Promise.all(['private', 'public'].map((s) =>
          allm('POST', `/api/v1/workspace/${WS[s]}/update-embeddings`, { body: { deletes: [docpath] }, headers: { 'content-type': 'application/json' } })
        ));
        const failed = detaches.filter((r) => r.status !== 200);
        if (failed.length) {
          // Log upstream detail server-side; return a generic message rather
          // than echoing raw ALLM internals (Copilot review, PR #141).
          console.error('[dashboard] delete detach failed:', failed.map((r) => (r.json && (r.json.error || r.json.message)) || r.status).join('; '));
          return { code: 502, body: { error: 'could not fully remove this document — it may still be embedded in one workspace' } };
        }
        // Only purge the underlying file once BOTH workspaces confirmed the
        // detach — purging on a partial failure would leave the failed
        // workspace referencing a file that's gone, breaking RAG there while
        // this response claimed success (Copilot review, PR #141).
        await allm('DELETE', '/api/v1/system/remove-documents', { body: { names: [docpath] }, headers: { 'content-type': 'application/json' } }).catch(() => null);
        // Drop any stale lock for the now-deleted doc so the set stays bounded.
        const s = readLocked(); if (s.delete(docpath)) writeLocked(s);
        return { code: 200, body: { ok: true } };
      });
      return send(res, out.code, out.body);
    }

    // ── private chat (proxied; customer never talks to ALLM directly) ──
    // Every message goes to a THREAD. A request without `thread` gets a new one
    // (returned as `thread`) and is never written to the workspace's shared
    // default conversation: that conversation sends its last N turns with every
    // question, so unrelated earlier chats leak into the answer (weown-fleet#55).
    const threadSlugOk = (s) => /^[a-z0-9][a-z0-9-]{0,64}$/i.test(String(s || ''));
    // Explicit unique slug instead of letting ALLM derive one from `name`.
    // Thread names come from the first message actually sent (deriveTitle()
    // client-side), so two different conversations easily share a name —
    // e.g. two chats both opening with "How much revenue have we
    // generated?". A name-derived slug would then resolve to the SAME
    // existing thread instead of creating a new one, silently merging one
    // conversation's history into another rather than stacking a new entry.
    const createThread = async (name) => {
      const slug = `t-${Date.now().toString(36)}-${crypto.randomBytes(4).toString('hex')}`;
      const r = await allm('POST', `/api/v1/workspace/${WS.private}/thread/new`, {
        body: { slug, name: String(name || '').slice(0, 80) || `Conversation ${new Date().toISOString().slice(0, 10)}` },
        headers: { 'content-type': 'application/json' },
      });
      const t = r.json && r.json.thread;
      return t ? { slug: t.slug, name: t.name } : { error: (r.json && (r.json.message || r.json.error)) || r.status };
    };
    if (p === '/api/chat' && req.method === 'POST') {
      // Larger body cap: optional base64 attachments ride on this JSON (ALLM
      // chat attachments API — mime application/anythingllm-document).
      const { message, thread, attachments: rawAtt } = await readBody(req, CHAT_BODY_MAX_BYTES);
      if (thread && !threadSlugOk(thread)) return send(res, 400, { error: 'bad thread' });
      const att = sanitizeChatAttachments(rawAtt);
      if (!att.ok) return send(res, 400, { error: att.error });
      const msg = String(message || '').trim()
        || (att.attachments ? 'Please review the attached file(s).' : '');
      if (!msg) return send(res, 400, { error: 'message required' });
      let created = null;
      if (!thread) {
        created = await createThread(msg.slice(0, 60));
        if (created.error) return send(res, 502, { error: 'could not start the conversation', detail: created.error });
      }
      const chatPath = `/api/v1/workspace/${WS.private}/thread/${thread || created.slug}/chat`;
      const chatBody = { message: msg, mode: 'chat' };
      if (att.attachments) chatBody.attachments = att.attachments;
      const r = await allm('POST', chatPath, { body: chatBody, headers: { 'content-type': 'application/json' } });
      // An upstream failure must be an error, not a 200 whose "text" is the raw
      // upstream error string — the UI renders {text} as a normal bot bubble.
      if (r.status !== 200 || !(r.json && r.json.textResponse))
        return send(res, 502, { error: (r.json && (r.json.error || r.json.message)) || 'the assistant is unavailable right now' });
      const out = { text: stripThink(r.json.textResponse), sources: (r.json.sources || []).map((s) => s.title).slice(0, 5) };
      if (created) out.thread = created;
      return send(res, 200, out);
    }

    // ── private chat threads (list / create / history / delete) ──
    if (p === '/api/threads' && req.method === 'GET') {
      const r = await allm('GET', `/api/v1/workspace/${WS.private}`);
      const wsObj = (r.json || {}).workspace;
      const w = Array.isArray(wsObj) ? wsObj[0] : wsObj;
      const threads = ((w && w.threads) || []).map((t) => ({ slug: t.slug, name: t.name }));
      return send(res, r.status === 200 ? 200 : 502, { threads });
    }
    if (p === '/api/threads' && req.method === 'POST') {
      const { name } = await readBody(req);
      const t = await createThread(name);
      if (t.error) return send(res, 502, { error: 'could not create the conversation', detail: t.error });
      return send(res, 200, t);
    }
    {
      const tm = p.match(/^\/api\/threads\/([A-Za-z0-9-]{1,64})\/(chats|delete|rename)$/);
      if (tm && tm[2] === 'chats' && req.method === 'GET') {
        const r = await allm('GET', `/api/v1/workspace/${WS.private}/thread/${tm[1]}/chats`);
        const history = ((r.json && r.json.history) || []).map((h) => ({ role: h.role, text: stripThink(h.content) }));
        return send(res, r.status === 200 ? 200 : 502, { history });
      }
      if (tm && tm[2] === 'delete' && req.method === 'POST') {
        const r = await allm('DELETE', `/api/v1/workspace/${WS.private}/thread/${tm[1]}`);
        return send(res, r.status === 200 ? 200 : 502, { ok: r.status === 200 });
      }
      if (tm && tm[2] === 'rename' && req.method === 'POST') {
        const { name } = await readBody(req);
        const clean = String(name || '').trim().slice(0, 80);
        if (!clean) return send(res, 400, { error: 'name required' });
        // Best-effort against ALLM's workspace-thread update route — unverified
        // against a live instance (no ALLM access from this dev environment).
        // If this 502s in practice, confirm the real path/payload and fix here.
        const r = await allm('POST', `/api/v1/workspace/${WS.private}/thread/${tm[1]}/update`, {
          body: { name: clean }, headers: { 'content-type': 'application/json' },
        });
        if (r.status !== 200) return send(res, 502, { error: 'could not rename the conversation', detail: (r.json && (r.json.message || r.json.error)) || r.status });
        return send(res, 200, { ok: true, name: clean });
      }
    }
    // Default-conversation history (the no-thread chat), for parity on load.
    if (p === '/api/chats' && req.method === 'GET') {
      const r = await allm('GET', `/api/v1/workspace/${WS.private}/chats`);
      const history = ((r.json && r.json.history) || []).map((h) => ({ role: h.role, text: stripThink(h.content) }));
      return send(res, r.status === 200 ? 200 : 502, { history });
    }

    // ── authorised websites (the embed's domain allowlist) ──
    if (p === '/api/embed-domains' && req.method === 'GET') {
      return send(res, 200, { domains: readDomains(), always: SELF_ORIGIN ? [SELF_ORIGIN] : [], configured: !!EMBED_ID });
    }
    if (p === '/api/embed-domains' && req.method === 'POST') {
      if (!EMBED_ID) return send(res, 400, { error: 'the chat widget is not provisioned yet — contact WeOwn support' });
      const body = await readBody(req);
      const input = Array.isArray(body.domains) ? body.domains : [];
      const bad = input.filter((d) => String(d || '').trim() && !normOrigin(d));
      if (bad.length) return send(res, 400, { error: `not a usable website address: ${bad.slice(0, 3).join(', ')} — use the form example.com (no wildcards, no page paths)` });
      // Self-origin is always retained, so the list can never become empty —
      // an empty allowlist is exactly the allow-any-site state this prevents.
      const list = dedupe([SELF_ORIGIN, ...input.map(normOrigin)]);
      if (!list.length) return send(res, 400, { error: 'at least one website is required' });
      const r = await allm('POST', `/api/v1/embed/${encodeURIComponent(EMBED_ID)}`,
        { body: { allowlist_domains: list.join(',') }, headers: { 'content-type': 'application/json' } });
      if (r.status !== 200 || !(r.json && r.json.success)) {
        return send(res, 502, { error: 'could not update the allowed websites', detail: (r.json && r.json.error) || r.status });
      }
      const persisted = writeDomains(list);
      return send(res, 200, { ok: true, domains: list, persisted });
    }

    // ── embed appearance (theme + logo metadata) ──
    if (p === '/api/embed-appearance' && req.method === 'GET') {
      const app = readAppearance();
      const theme = resolveTheme(app);
      return send(res, 200, {
        themeId: app.themeId,
        accentOverride: app.accentOverride || '',
        assistantName: app.assistantName || '',
        hasCustomLogo: !!app.logo,
        logoUrl: app.logo
          ? `${BASE}/brand/logo?v=${encodeURIComponent(app.logo.updatedAt || '1')}`
          : `${BASE}/brand/weownchat-mark.svg`,
        logoMaxBytes: LOGO_MAX_BYTES,
        logoExts: [...LOGO_EXTS],
        resolved: theme,
        themes: Object.values(EMBED_THEMES).map((t) => ({
          id: t.id, name: t.name, blurb: t.blurb,
          buttonColor: t.buttonColor, userBgColor: t.userBgColor,
          assistantBgColor: t.assistantBgColor, chatIcon: t.chatIcon,
        })),
      });
    }
    if (p === '/api/embed-appearance' && req.method === 'POST') {
      return await withAppearanceLock(async () => {
      const body = await readBody(req);
      const app = readAppearance();
      if (body.themeId != null) {
        const tid = String(body.themeId || '').trim();
        if (!EMBED_THEMES[tid]) return send(res, 400, { error: 'unknown theme' });
        app.themeId = tid;
      }
      if (body.accentOverride != null) {
        const a = String(body.accentOverride || '').trim();
        if (a && !isHexColor(a)) return send(res, 400, { error: 'accent must be a hex color like #00A3FF (or empty to clear)' });
        app.accentOverride = a;
      }
      if (body.assistantName != null) {
        app.assistantName = String(body.assistantName || '').trim().slice(0, 60);
      }
      if (body.useDefaultLogo === true) {
        clearCustomLogoFiles();
        app.logo = null;
      }
      const persisted = writeAppearance(app);
      const theme = resolveTheme(app);
      return send(res, 200, {
        ok: true, persisted, themeId: app.themeId, accentOverride: app.accentOverride || '',
        assistantName: app.assistantName || '', hasCustomLogo: !!app.logo,
        logoUrl: app.logo
          ? `${BASE}/brand/logo?v=${encodeURIComponent(app.logo.updatedAt || '1')}`
          : `${BASE}/brand/weownchat-mark.svg`,
        resolved: theme,
      });
      });
    }

    // Raw body logo upload (File as request body + X-Upload-Filename) — same
    // header convention as /api/upload, but stored locally under STATE_DIR.
    if (p === '/api/embed-logo' && req.method === 'POST') {
      return await withAppearanceLock(async () => {
      const fname = req.headers['x-upload-filename'] || '';
      const ext = logoExtFromName(fname);
      if (!LOGO_EXTS.has(ext)) {
        req.resume();
        return send(res, 400, { error: 'logo must be png, jpg, webp, or svg (square ~256–512px works best)' });
      }
      const cl = parseInt(req.headers['content-length'] || '0', 10);
      if (cl && cl > LOGO_MAX_BYTES) {
        req.resume();
        return send(res, 400, { error: `logo is too large — max ${Math.round(LOGO_MAX_BYTES / 1048576 * 10) / 10} MB` });
      }
      let buf;
      try { buf = await readRawBody(req, LOGO_MAX_BYTES); }
      catch (e) {
        if (e.code === 'TOO_LARGE') return send(res, 400, { error: `logo is too large — max ${Math.round(LOGO_MAX_BYTES / 1048576 * 10) / 10} MB` });
        console.error('[dashboard] logo upload read:', e.message);
        return send(res, 400, { error: 'could not read the upload' });
      }
      if (!buf.length) return send(res, 400, { error: 'empty upload' });
      if (ext === 'svg') {
        if (!looksLikeSvg(buf) || !svgLooksSafe(buf))
          return send(res, 400, { error: 'that SVG looks unsafe or invalid — try PNG or JPG instead' });
      } else {
        // Magic-byte sniff — claimed extension must match file contents.
        const isPng = buf.length >= 4 && buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47;
        const isJpg = buf.length >= 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff;
        const isWebp = buf.length >= 12
          && buf[0] === 0x52 && buf[1] === 0x49 && buf[2] === 0x46 && buf[3] === 0x46
          && buf[8] === 0x57 && buf[9] === 0x45 && buf[10] === 0x42 && buf[11] === 0x50;
        const ok = (ext === 'png' && isPng) || (ext === 'jpg' && isJpg) || (ext === 'webp' && isWebp);
        if (!ok) return send(res, 400, { error: 'file contents do not match the claimed image type' });
      }
      try {
        fs.mkdirSync(BRAND_DIR, { recursive: true });
        clearCustomLogoFiles();
        const dest = path.join(BRAND_DIR, `logo.${ext}`);
        const tmp = `${dest}.${process.pid}.tmp`;
        fs.writeFileSync(tmp, buf);
        fs.renameSync(tmp, dest);
        const app = readAppearance();
        app.logo = { ext, mime: LOGO_MIME[ext], updatedAt: new Date().toISOString() };
        const persisted = writeAppearance(app);
        return send(res, 200, {
          ok: true, persisted, hasCustomLogo: true,
          logoUrl: `${BASE}/brand/logo?v=${encodeURIComponent(app.logo.updatedAt)}`,
        });
      } catch (e) {
        console.error('[dashboard] logo save:', e.message);
        return send(res, 502, { error: 'could not save the logo' });
      }
      });
    }
    if (p === '/api/embed-logo' && req.method === 'DELETE') {
      return await withAppearanceLock(async () => {
      const app = readAppearance();
      clearCustomLogoFiles();
      app.logo = null;
      const persisted = writeAppearance(app);
      return send(res, 200, {
        ok: true, persisted, hasCustomLogo: false,
        logoUrl: `${BASE}/brand/weownchat-mark.svg`,
      });
      });
    }

    // ── booking CTA settings ──
    if (p === '/api/booking' && req.method === 'GET') {
      const b = readBooking();
      return send(res, 200, { url: b.url, label: b.label });
    }
    if (p === '/api/booking' && req.method === 'POST') {
      const body = await readBody(req);
      const rawUrl = body && body.url != null ? String(body.url) : '';
      const rawLabel = body && body.label != null ? String(body.label).trim() : '';
      const checked = validateBookingUrl(rawUrl);
      if (!checked.ok) return send(res, 400, { error: checked.error });
      // Empty URL clears the booking CTA (and any label).
      const url = checked.url;
      let label = '';
      if (url) {
        label = rawLabel || DEFAULT_BOOKING_LABEL;
        if (label.length > 80) return send(res, 400, { error: 'label is too long (max 80 characters)' });
      }
      const persisted = writeBooking(url, label);
      return send(res, 200, { ok: true, url, label, persisted });
    }

    // ── embed snippet ──
    if (p === '/api/snippet' && req.method === 'GET') {
      if (!EMBED_ID) return send(res, 200, { snippet: '', note: 'Embed not provisioned yet — contact WeOwn support.' });
      const d = PUBLIC_DOMAIN || 'YOUR-INSTANCE-DOMAIN';
      // data-greeting carries the AI disclaimer the moment the widget opens, so
      // it is stated before the visitor types anything (PRD §3, non-negotiable).
      const greeting = "Hi! I'm an AI assistant. Everything here is general information only — please verify it for your own situation, and don't share private information in this chat.";
      const app = readAppearance();
      const theme = resolveTheme(app);
      // Prefer custom logo URL; otherwise the built-in WeOwn mark.
      const brandUrl = app.logo
        ? `https://${d}${BASE}/brand/logo?v=${encodeURIComponent(app.logo.updatedAt || '1')}`
        : `https://${d}${BASE}/brand/weownchat-mark.svg`;
      // Always hide ALLM sponsor chrome (data-no-sponsor). Booking uses a
      // companion floating button near the launcher when URL is set — not
      // data-sponsor-text/link (avoids dual CTAs / AnythingLLM sponsor chrome).
      const booking = readBooking();
      const bookingBtnColor = theme.buttonColor;
      const bookingTextColor = contrastInk(bookingBtnColor);
      let snippet =
        `<script data-embed-id="${escAttr(EMBED_ID)}"\n` +
        `  data-base-api-url="https://${escAttr(d)}/api/embed"\n` +
        `  data-greeting="${escAttr(greeting)}"\n` +
        `  data-brand-image-url="${escAttr(brandUrl)}"\n` +
        `  data-button-color="${escAttr(theme.buttonColor)}"\n` +
        `  data-user-bg-color="${escAttr(theme.userBgColor)}"\n` +
        `  data-assistant-bg-color="${escAttr(theme.assistantBgColor)}"\n` +
        `  data-chat-icon="${escAttr(theme.chatIcon)}"\n`;
      if (app.assistantName) {
        snippet += `  data-assistant-name="${escAttr(app.assistantName)}"\n`;
      }
      snippet +=
        `  data-no-sponsor="true"\n` +
        `  src="https://${escAttr(d)}/embed/anythingllm-chat-widget.min.js"><\/script>`;
      if (booking.url) {
        const label = booking.label || DEFAULT_BOOKING_LABEL;
        // JSON.stringify for safe JS string literals inside the companion script.
        // Prefer stacking above the AnythingLLM launcher when we can find it;
        // otherwise sit clear of a typical 56px FAB (safe-area aware).
        snippet += `\n<script>(function(){` +
          `var u=${jsonForScript(booking.url)},t=${jsonForScript(label)},c=${jsonForScript(bookingBtnColor)},ink=${jsonForScript(bookingTextColor)},relMode=false,tries=0;` +
          `function findLauncher(){` +
          `var sels=['[id*=\"anything-llm\" i]','[class*=\"anything-llm\" i]','[id*=\"allm-\" i]','[class*=\"allm-\" i]','button[aria-label*=\"chat\" i]'];` +
          `for(var i=0;i<sels.length;i++){try{var n=document.querySelector(sels[i]);if(n){var cs=getComputedStyle(n);if(cs.position==='fixed'||cs.position==='absolute')return n;}}catch(e){}}` +
          `var btns=document.querySelectorAll('button');` +
          `for(var j=0;j<btns.length;j++){var el=btns[j],s=getComputedStyle(el);` +
          `if(s.position!=='fixed')continue;var b=parseFloat(s.bottom)||0,r=parseFloat(s.right)||0;` +
          `if(b>=0&&b<140&&r>=0&&r<140&&el.offsetWidth&&el.offsetWidth<=80)return el;}` +
          `return null;}` +
          `function place(b){` +
          `var rel=findLauncher();relMode=!!rel;` +
          `if(rel){var r=rel.getBoundingClientRect();` +
          `b.style.right=Math.max(16,window.innerWidth-r.right)+'px';` +
          `b.style.bottom=(Math.max(0,window.innerHeight-r.top)+12)+'px';` +
          `b.style.left='auto';}` +
          `else{b.style.right='max(16px, env(safe-area-inset-right, 0px))';` +
          `b.style.bottom='calc(24px + 56px + 12px)';b.style.left='auto';}` +
          `}` +
          `function mount(){` +
          `var b=document.getElementById('weown-booking-cta');` +
          `if(!b){` +
          `b=document.createElement('button');` +
          `b.id='weown-booking-cta';b.type='button';b.textContent=t;` +
          `b.setAttribute('aria-label',t);b.setAttribute('data-no-sponsor','true');` +
          `b.style.cssText='position:fixed;z-index:2147483646;` +
          `background:'+c+';color:'+ink+';border:0;border-radius:999px;padding:12px 18px;` +
          `font:600 14px/1.2 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;` +
          `box-shadow:0 4px 14px rgba(0,0,0,.28);cursor:pointer;max-width:min(240px,calc(100vw - 40px));` +
          `white-space:nowrap;overflow:hidden;text-overflow:ellipsis';` +
          `b.addEventListener('click',function(){window.open(u,'_blank','noopener,noreferrer');});` +
          `document.body.appendChild(b);` +
          `}` +
          `place(b);` +
          `}` +
          `function onResize(){var b=document.getElementById('weown-booking-cta');if(b)place(b);}` +
          `function retry(){mount();if(!relMode&&tries++<8)setTimeout(retry,500);}` +
          `if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',retry);else retry();` +
          `window.addEventListener('resize',onResize);` +
          `})();<\/script>`;
      }
      return send(res, 200, { snippet });
    }

    return send(res, 404, { error: 'not found' });
  } catch (e) {
    console.error('[dashboard]', e.message);
    send(res, 500, { error: 'internal error' });
  }
});

server.listen(PORT, () => console.log(`dashboard ${VERSION} listening :${PORT} base=${BASE} allm=${ALLM_URL} ws=${WS.public}/${WS.private}`));
