// {{ project_name }} customer dashboard — zero-dependency Node server.
// (Plain JS, no jinja vars: all instance config arrives via environment,
// injected at container start by the Infisical entrypoint wrapper.)
//
// WHAT THIS IS: the customer's ONLY surface. They authenticate HERE (never to
// AnythingLLM), and this server proxies scoped actions to the ALLM API with
// the admin Developer API key held server-side. Two sections:
//   Public  -> workspace WS_PUBLIC_SLUG  (grounds the website embed widget)
//   Private -> workspace WS_PRIVATE_SLUG (their business docs + private chat)
//
// Zero npm dependencies by design: no supply chain, no install step at deploy.
// Uploads and chat are streamed/proxied raw — this server never parses
// multipart bodies, it just authenticates, scopes, and forwards.
//
// Required env (Infisical): ALLM_ADMIN_API_KEY, DASHBOARD_PASSWORD_HASH
// (sha256 hex of the customer password), DASHBOARD_SESSION_SECRET.
// Optional env: DASHBOARD_CUSTOMER_EMAIL, WS_PUBLIC_SLUG, WS_PRIVATE_SLUG,
// EMBED_ID, EMBED_ALLOWLIST_DOMAINS, PUBLIC_DOMAIN, ALLM_URL, PORT, BASE_PATH,
// DASHBOARD_STATE_DIR, UPLOAD_ALLOWED_EXT, UPLOAD_MAX_BYTES.
'use strict';
const http = require('http');
const https = require('https');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const PORT = parseInt(process.env.PORT || '3000', 10);
const BASE = process.env.BASE_PATH || '/app';
const ALLM_URL = process.env.ALLM_URL || 'http://anythingllm:3001';
const API_KEY = process.env.ALLM_ADMIN_API_KEY || '';
// Customer-facing billing portal (subscription, invoices, affiliate earnings).
// Optional: instances without it simply don't show the billing link.
const BILLING_URL = process.env.BILLING_URL || '';
// scrypt (memory-hard KDF, built into node crypto — no npm dep). Format:
// scrypt$<salthex>$<hashhex>. Never a fast hash: a leaked Infisical value must
// not be brute-forceable. Generated by scripts/bootstrap-product.sh.
const PW_HASH = process.env.DASHBOARD_PASSWORD_HASH || '';
function verifyPassword(pw) {
  const parts = PW_HASH.split('$');
  if (parts.length !== 3 || parts[0] !== 'scrypt') return false;
  let salt, expected, actual;
  try {
    salt = Buffer.from(parts[1], 'hex');
    expected = Buffer.from(parts[2], 'hex');
    actual = crypto.scryptSync(pw || '', salt, expected.length);
  } catch { return false; }
  return actual.length === expected.length && crypto.timingSafeEqual(actual, expected);
}
const SESSION_SECRET = process.env.DASHBOARD_SESSION_SECRET || '';
const CUSTOMER_EMAIL = (process.env.DASHBOARD_CUSTOMER_EMAIL || '').toLowerCase();
const WS = { public: process.env.WS_PUBLIC_SLUG || 'ws-public', private: process.env.WS_PRIVATE_SLUG || 'ws-private' };
const EMBED_ID = process.env.EMBED_ID || '';
const PUBLIC_DOMAIN = process.env.PUBLIC_DOMAIN || '';
const VERSION = process.env.DASHBOARD_VERSION || 'v0';

// ── embed domain allowlist ───────────────────────────────────────────────────
// AnythingLLM will answer an embed from ANY website unless the embed carries an
// allowlist (a NULL allowlist means allow-all), so the customer's bot — and
// their capped LLM budget — is only theirs once this list is set. The list is
// seeded by provisioning (EMBED_ALLOWLIST_DOMAINS) and owned by the customer
// from their first save here, so adding a second website never needs an
// operator. It can never be emptied: this instance's own origin is always in it.
//
// ALLM compares the browser's Origin header to the stored strings EXACTLY, so
// every entry must be "scheme://host[:port]" — lower-cased, no path, no trailing
// slash, no wildcards (ALLM does not support them).
const STATE_DIR = process.env.DASHBOARD_STATE_DIR || '/state';
const DOMAINS_FILE = path.join(STATE_DIR, 'embed-domains.json');
const normOrigin = (raw) => {
  let s = String(raw || '').trim().toLowerCase();
  if (!s) return null;
  if (!/^https?:\/\//.test(s)) s = `https://${s}`;
  let u; try { u = new URL(s); } catch { return null; }
  if (!u.hostname.includes('.') || /[^a-z0-9.-]/.test(u.hostname)) return null;
  return `${u.protocol}//${u.hostname}${u.port ? `:${u.port}` : ''}`;
};
const dedupe = (list) => [...new Set(list.filter(Boolean))];
const SELF_ORIGIN = normOrigin(PUBLIC_DOMAIN);
const seedDomains = () => dedupe((process.env.EMBED_ALLOWLIST_DOMAINS || '').split(',').map(normOrigin));
const readDomains = () => {
  try { return dedupe(JSON.parse(fs.readFileSync(DOMAINS_FILE, 'utf8')).domains.map(normOrigin)); }
  catch { return seedDomains(); }
};
const writeDomains = (list) => {
  try {
    fs.mkdirSync(STATE_DIR, { recursive: true });
    fs.writeFileSync(DOMAINS_FILE, JSON.stringify({ domains: list, savedAt: new Date().toISOString() }, null, 2));
    return true;
  } catch (e) { console.error('[dashboard] could not persist embed domains:', e.message); return false; }
};

// ── document locks ───────────────────────────────────────────────────────────
// The shared document library (see /api/documents below) is used by every
// conversation in the workspace — deleting a document doesn't just affect the
// chat you're in, it silently pulls grounding out from under every other
// conversation too. AnythingLLM has no concept of a "locked" document, so this
// is dashboard-only state (same STATE_DIR + read/write pattern as the embed
// allowlist above): a docpath in this set can't be deleted until unlocked
// again, whether or not the client-side UI agrees.
const LOCKED_FILE = path.join(STATE_DIR, 'locked-documents.json');
const readLocked = () => {
  try { return new Set(JSON.parse(fs.readFileSync(LOCKED_FILE, 'utf8')).docpaths || []); }
  catch (e) {
    // No file yet = nothing locked (normal first run). A file that EXISTS but
    // won't parse is corruption we must not hide behind a silent empty set —
    // log it loudly. The atomic write below makes crash-corruption impossible,
    // so this should never fire in practice (Copilot review, PR #141).
    if (e.code !== 'ENOENT') console.error('[dashboard] locked-documents.json unreadable — treating as empty:', e.message);
    return new Set();
  }
};
const writeLocked = (set) => {
  try {
    fs.mkdirSync(STATE_DIR, { recursive: true });
    // Atomic replace: write a temp file then rename over the target. A crash
    // mid-write can then never leave a truncated file that silently unlocks
    // EVERY document — the lock is a safety control (Copilot review, PR #141).
    const tmp = `${LOCKED_FILE}.${process.pid}.tmp`;
    fs.writeFileSync(tmp, JSON.stringify({ docpaths: [...set], savedAt: new Date().toISOString() }, null, 2));
    fs.renameSync(tmp, LOCKED_FILE);
    return true;
  } catch (e) { console.error('[dashboard] could not persist document locks:', e.message); return false; }
};

// Serialize every read-modify-write of the lock file and every
// check-then-purge, so two concurrent document operations can't clobber each
// other's lock change, nor let a just-locked document slip through a purge that
// already read the old state (Copilot review, PR #141). Single tenant, so
// contention is rare — but the lock is a safety control and must be race-free.
let _docOpChain = Promise.resolve();
const withDocLock = (fn) => {
  const run = _docOpChain.then(fn, fn);
  _docOpChain = run.then(() => {}, () => {});
  return run;
};

// ── upload policy (locked-down release) ──────────────────────────────────────
// The uploader is the authenticated PRACTICE OWNER uploading their OWN grounding
// documents (service guide, fee schedule, Q&A sheet) — per the PRD the supported
// set is PDF / Markdown / plain text / CSV. End-customer document intake is NOT
// this endpoint: the public bot redirects those to the practice's own portal.
// Anything outside the allowlist is refused BEFORE a byte reaches AnythingLLM.
const UPLOAD_ALLOWED_EXT = (process.env.UPLOAD_ALLOWED_EXT || 'pdf,md,markdown,txt,csv')
  .split(',').map((s) => s.trim().toLowerCase()).filter(Boolean);
const UPLOAD_MAX_BYTES = parseInt(process.env.UPLOAD_MAX_BYTES || String(25 * 1024 * 1024), 10);
// Filename arrives in the X-Upload-Filename header (the dashboard sets it) so we can
// enforce the allowlist without parsing multipart. Belt-and-braces: the browser also
// constrains it via the file input's accept=, and the byte cap below is enforced on
// the live stream regardless of what any header claims.
const extOf = (name) => {
  const m = /\.([A-Za-z0-9]+)\s*$/.exec(String(name || '').trim());
  return m ? m[1].toLowerCase() : '';
};
const uploadRejection = (name, len) => {
  const ext = extOf(name);
  if (!name) return 'missing filename (X-Upload-Filename)';
  if (!ext || !UPLOAD_ALLOWED_EXT.includes(ext)) {
    return `file type ".${ext || '?'}" is not accepted — allowed: ${UPLOAD_ALLOWED_EXT.join(', ')}`;
  }
  if (len && Number(len) > UPLOAD_MAX_BYTES) {
    return `file is too large (${Math.round(Number(len) / 1048576)} MB) — limit is ${Math.round(UPLOAD_MAX_BYTES / 1048576)} MB`;
  }
  return null;
};

for (const [k, v] of Object.entries({ ALLM_ADMIN_API_KEY: API_KEY, DASHBOARD_PASSWORD_HASH: PW_HASH, DASHBOARD_SESSION_SECRET: SESSION_SECRET })) {
  if (!v) { console.error(`refusing to start: ${k} not injected — set it in Infisical`); process.exit(1); }
}

// ── OIDC login (Keycloak `weown-chat` realm) ─────────────────────────────────
// Provisioned per tenant by weown-fleet/scripts/kc-provision-tenant.sh, which
// stores OIDC_ISSUER / OIDC_CLIENT_ID / OIDC_CLIENT_SECRET / OIDC_ALLOWED_GROUP
// in the tenant's Infisical folder — when they're present the login page offers
// "Sign in with WeOwn" (authorization-code flow, server-side exchange; the
// browser never sees tokens). Authorization = membership of the tenant group in
// the userinfo `groups` claim. The password login stays as break-glass.
// Zero-dependency: plain https + the same HMAC session cookie as passwords.
const OIDC = {
  issuer: (process.env.OIDC_ISSUER || '').replace(/\/$/, ''),
  clientId: process.env.OIDC_CLIENT_ID || '',
  clientSecret: process.env.OIDC_CLIENT_SECRET || '',
  group: process.env.OIDC_ALLOWED_GROUP || '',
};
const oidcEnabled = () => !!(OIDC.issuer && OIDC.clientId && OIDC.clientSecret && OIDC.group);
const oidcRedirectUri = () => `https://${PUBLIC_DOMAIN}${BASE}/oidc/callback`;
const libFor = (u) => (u.protocol === 'https:' ? https : http);
const postForm = (urlStr, form) => new Promise((resolve, reject) => {
  const u = new URL(urlStr);
  const body = new URLSearchParams(form).toString();
  const req = libFor(u).request(u, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': Buffer.byteLength(body) } }, (res) => {
    let d = ''; res.on('data', (c) => (d += c));
    res.on('end', () => { try { resolve({ status: res.statusCode, json: JSON.parse(d) }); } catch { resolve({ status: res.statusCode, json: null }); } });
  });
  req.on('error', reject); req.setTimeout(30e3, () => req.destroy(new Error('OIDC request timeout')));
  req.end(body);
});
const getJson = (urlStr, bearer) => new Promise((resolve, reject) => {
  const u = new URL(urlStr);
  const req = libFor(u).request(u, { method: 'GET', headers: { Authorization: `Bearer ${bearer}` } }, (res) => {
    let d = ''; res.on('data', (c) => (d += c));
    res.on('end', () => { try { resolve({ status: res.statusCode, json: JSON.parse(d) }); } catch { resolve({ status: res.statusCode, json: null }); } });
  });
  req.on('error', reject); req.setTimeout(30e3, () => req.destroy(new Error('OIDC request timeout')));
  req.end();
});

// ── sessions: HMAC-signed expiry cookie, SameSite=Strict ─────────────────────
const hmac = (s) => crypto.createHmac('sha256', SESSION_SECRET).update(s).digest('hex');
const makeSession = () => { const exp = Date.now() + 12 * 3600e3; return `${exp}.${hmac(String(exp))}`; };
const validSession = (c) => {
  const m = /(?:^|;\s*)dsession=([^;]+)/.exec(c || ''); if (!m) return false;
  const [exp, sig] = m[1].split('.'); if (!exp || !sig) return false;
  try {
    return Number(exp) > Date.now() &&
      crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(hmac(exp)));
  } catch { return false; }
};

// naive login rate limit: 10 attempts / 10 min per IP
const attempts = new Map();
const throttled = (ip) => {
  const now = Date.now();
  const a = (attempts.get(ip) || []).filter((t) => now - t < 600e3);
  attempts.set(ip, a);
  return a.length >= 10;
};

// ── ALLM proxy helper ────────────────────────────────────────────────────────
function allm(method, apiPath, { body, headers, stream } = {}) {
  return new Promise((resolve, reject) => {
    const u = new URL(apiPath, ALLM_URL);
    const lib = u.protocol === 'https:' ? https : http;
    const req = lib.request(u, { method, headers: { Authorization: `Bearer ${API_KEY}`, Accept: 'application/json', ...headers } }, (res) => {
      let data = '';
      res.on('data', (c) => (data += c));
      res.on('end', () => {
        let json = null; try { json = JSON.parse(data); } catch { /* non-JSON */ }
        resolve({ status: res.statusCode, json, raw: data });
      });
    });
    req.on('error', reject);
    req.setTimeout(240e3, () => req.destroy(new Error('ALLM request timeout')));
    if (stream) stream.pipe(req);
    else { if (body !== undefined) req.end(JSON.stringify(body)); else req.end(); }
  });
}

const send = (res, code, obj, extra = {}) => {
  const body = typeof obj === 'string' ? obj : JSON.stringify(obj);
  res.writeHead(code, { 'Content-Type': typeof obj === 'string' ? 'text/html; charset=utf-8' : 'application/json', 'Cache-Control': 'no-store', ...extra });
  res.end(body);
};
const page = (name) => fs.readFileSync(path.join(__dirname, 'public', name), 'utf8');
// Reasoning models (DeepSeek/Kimi) emit <think>…</think> blocks that AnythingLLM
// passes through verbatim — customers must never see the model's internal
// reasoning (it narrates their documents back at them). Strip everywhere chat
// text leaves this server: live replies and stored history.
const stripThink = (t) => String(t || '').replace(/<think>[\s\S]*?<\/think>/gi, '').trim();

const readBody = (req) => new Promise((r) => {
  // These endpoints carry tiny JSON (a docpath and a couple of flags). Cap the
  // buffer so an authenticated client can't grow the process heap with a huge
  // body; over the cap we stop reading and resolve empty, which the handlers'
  // own validation then rejects as a 400 (Copilot review, PR #141).
  let d = '', len = 0, over = false;
  req.on('data', (c) => { len += c.length; if (over) return; if (len > 262144) { over = true; d = ''; req.destroy(); return; } d += c; });
  req.on('end', () => { try { r(JSON.parse(d || '{}')); } catch { r({}); } });
  req.on('error', () => r({}));
});

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, 'http://x');
    let p = url.pathname;
    if (p === '/healthz') return send(res, 200, { ok: true });
    if (!p.startsWith(BASE)) return send(res, 302, 'redirecting', { Location: BASE + '/' });
    p = p.slice(BASE.length) || '/';
    // Public health probe. Caddy only routes /app* here, so `/healthz` above is
    // unreachable from outside the compose network — a deploy check against the
    // public URL has to be able to hit BASE + /healthz, before any auth.
    if (p === '/healthz') return send(res, 200, { ok: true });
    const authed = validSession(req.headers.cookie);

    // CSRF: all state-changing calls must carry the custom header (fetch-only)
    if (req.method !== 'GET' && req.headers['x-dashboard'] !== '1' && p !== '/api/login')
      return send(res, 403, { error: 'missing X-Dashboard header' });

    // ── auth ──
    if (p === '/api/login' && req.method === 'POST') {
      const ip = req.socket.remoteAddress || '?';
      if (throttled(ip)) return send(res, 429, { error: 'too many attempts — wait 10 minutes' });
      const { email, password } = await readBody(req);
      const ok = verifyPassword(password) &&
                 (!CUSTOMER_EMAIL || (email || '').toLowerCase() === CUSTOMER_EMAIL);
      if (!ok) { attempts.get(ip).push(Date.now()); return send(res, 401, { error: 'invalid credentials' }); }
      return send(res, 200, { ok: true }, { 'Set-Cookie': `dsession=${makeSession()}; Path=${BASE}; HttpOnly; SameSite=Strict; Secure; Max-Age=43200` });
    }
    if (p === '/api/logout' && req.method === 'POST')
      return send(res, 200, { ok: true }, { 'Set-Cookie': `dsession=x; Path=${BASE}; HttpOnly; SameSite=Strict; Secure; Max-Age=0` });

    // ── OIDC (GET-only flow; state is HMAC-signed so no server-side session) ──
    if (p === '/api/authcfg' && req.method === 'GET')
      return send(res, 200, { oidc: oidcEnabled() });
    if (p === '/oidc/login' && req.method === 'GET') {
      if (!oidcEnabled()) return send(res, 404, { error: 'SSO not configured' });
      const st = `${Date.now()}.${crypto.randomBytes(8).toString('hex')}`;
      const state = `${st}.${hmac(`oidc:${st}`)}`;
      const auth = `${OIDC.issuer}/protocol/openid-connect/auth?` + new URLSearchParams({
        client_id: OIDC.clientId, redirect_uri: oidcRedirectUri(),
        response_type: 'code', scope: 'openid email', state,
      }).toString();
      return send(res, 302, 'redirecting', { Location: auth });
    }
    if (p === '/oidc/callback' && req.method === 'GET') {
      if (!oidcEnabled()) return send(res, 404, { error: 'SSO not configured' });
      const code = url.searchParams.get('code') || '';
      const state = url.searchParams.get('state') || '';
      const m = /^(\d+)\.([0-9a-f]+)\.([0-9a-f]+)$/.exec(state);
      const stateOk = !!m && Number(m[1]) > Date.now() - 600e3 && (() => {
        try { return crypto.timingSafeEqual(Buffer.from(m[3]), Buffer.from(hmac(`oidc:${m[1]}.${m[2]}`))); } catch { return false; }
      })();
      if (!code || !stateOk) return send(res, 400, { error: 'invalid SSO state — start again at ' + BASE + '/' });
      const tok = await postForm(`${OIDC.issuer}/protocol/openid-connect/token`, {
        grant_type: 'authorization_code', code, redirect_uri: oidcRedirectUri(),
        client_id: OIDC.clientId, client_secret: OIDC.clientSecret,
      });
      const access = tok.json && tok.json.access_token;
      if (tok.status !== 200 || !access) { console.error('[dashboard] OIDC token exchange failed:', tok.status); return send(res, 401, { error: 'SSO sign-in failed' }); }
      // userinfo comes from the issuer over TLS — no local JWT verification
      // needed, the source of truth is asked directly.
      const ui = await getJson(`${OIDC.issuer}/protocol/openid-connect/userinfo`, access);
      const groups = (ui.json && ui.json.groups) || [];
      if (ui.status !== 200 || !Array.isArray(groups) || !groups.includes(OIDC.group)) {
        console.error('[dashboard] OIDC login rejected: not in', OIDC.group);
        return send(res, 403, { error: 'this account is not authorized for this dashboard — ask WeOwn support to add you' });
      }
      return send(res, 302, 'redirecting', {
        Location: BASE + '/',
        'Set-Cookie': `dsession=${makeSession()}; Path=${BASE}; HttpOnly; SameSite=Lax; Secure; Max-Age=43200`,
      });
    }

    // ── pages ──
    if (p === '/' || p === '') return send(res, 200, page(authed ? 'index.html' : 'login.html'));
    if (p === '/version') return send(res, 200, { version: VERSION });

    if (!authed) return send(res, 401, { error: 'not authenticated' });

    // ── identity (sidebar display only — not a secret, just never shown to
    // the client until now; DASHBOARD_CUSTOMER_EMAIL is optional, so this
    // may come back null on instances that don't set it) ──
    if (p === '/api/whoami' && req.method === 'GET')
      return send(res, 200, { email: CUSTOMER_EMAIL || null, billingUrl: BILLING_URL || null });

    // ── documents: one shared library, not two separate uploads. A document
    // is independently on/off for each workspace (adds/deletes via
    // update-embeddings); "the library" is just the union of what's embedded
    // in WS.private and WS.public — every upload attaches to at least one of
    // them immediately (see X-Upload-Scope below), so nothing is ever
    // orphaned in the system store with no scope pointing at it. This reuses
    // only ALLM calls already proven by the pre-redesign per-scope endpoints
    // (workspace GET, update-embeddings adds/deletes, system remove-documents)
    // — no new/unverified ALLM surface for this feature. ──
    const docsOf = async (scope) => {
      const r = await allm('GET', `/api/v1/workspace/${WS[scope]}`);
      // Verified against a live ALLM (2026-08-05): GET /api/v1/workspace/<slug>
      // returns { workspace: [ { ..., documents: [] } ] } — `workspace` is an
      // ARRAY, and even an EMPTY workspace includes `documents: []`. So a 200
      // that does NOT yield a documents array is an UNEXPECTED shape, never a
      // legitimate "no documents". Return ok:false there, so the destructive
      // orphan-purge in the scope handler fails loud instead of deleting a
      // document that may in fact still be embedded in the other workspace
      // (Copilot review, PR #141).
      const wsList = (r.json || {}).workspace;
      const ws = Array.isArray(wsList) ? wsList[0] : wsList;
      const docs = ws && Array.isArray(ws.documents) ? ws.documents : null;
      return { ok: r.status === 200 && docs !== null, docs: docs || [] };
    };
    if (p === '/api/documents' && req.method === 'GET') {
      const [priv, pub] = await Promise.all([docsOf('private'), docsOf('public')]);
      if (!priv.ok && !pub.ok) return send(res, 502, { error: 'could not load documents' });
      // metadata is ALLM-controlled JSON text, not something this server
      // writes — a malformed/legacy blob must fall back to the docpath, not
      // 500 the whole /api/documents response (Copilot review, PR #141).
      const nameOf = (d) => {
        if (!d.metadata) return d.docpath;
        try { return JSON.parse(d.metadata).title || d.docpath; }
        catch { return d.docpath; }
      };
      const locked = readLocked();
      const byPath = new Map();
      priv.docs.forEach((d) => byPath.set(d.docpath, { id: d.id, path: d.docpath, name: nameOf(d), private: true, public: false, locked: locked.has(d.docpath) }));
      pub.docs.forEach((d) => {
        const existing = byPath.get(d.docpath);
        if (existing) existing.public = true;
        else byPath.set(d.docpath, { id: d.id, path: d.docpath, name: nameOf(d), private: false, public: true, locked: locked.has(d.docpath) });
      });
      return send(res, 200, { documents: [...byPath.values()] });
    }
    if (p === '/api/documents/lock' && req.method === 'POST') {
      const { docpath, locked: wantLocked } = await readBody(req);
      if (!docpath) return send(res, 400, { error: 'docpath required' });
      // Same boolean discipline as /api/documents/scope's `on` — a malformed
      // `locked` must not be coerced into an accidental unlock (or, e.g., a
      // truthy string like "false" into an accidental lock)
      // (Copilot review, PR #141).
      if (typeof wantLocked !== 'boolean') return send(res, 400, { error: 'locked must be true or false' });
      // Read-modify-write under the mutex so a concurrent lock/unlock or a
      // purge can't clobber this change (Copilot review, PR #141).
      const saved = await withDocLock(async () => {
        const set = readLocked();
        if (wantLocked) set.add(docpath); else set.delete(docpath);
        // writeLocked()'s return value was previously ignored, so a failed
        // write (disk full, permissions) still reported {ok:true} — the client
        // would believe the lock took even though it evaporates on next read
        // (Copilot review, PR #141).
        return writeLocked(set);
      });
      if (!saved) return send(res, 502, { error: 'could not save the lock — try again' });
      return send(res, 200, { ok: true, locked: wantLocked });
    }
    if (p === '/api/upload' && req.method === 'POST') {
      // Locked-down upload policy: refuse disallowed types / oversized files BEFORE
      // any byte reaches AnythingLLM.
      const fname = req.headers['x-upload-filename'] || '';
      const scope = req.headers['x-upload-scope'] === 'public' ? 'public' : 'private';
      const reject = uploadRejection(fname, req.headers['content-length']);
      if (reject) {
        req.resume(); // drain so the client gets the response instead of a reset
        return send(res, 400, { error: reject });
      }
      // Enforce the byte cap on the live stream too — content-length may be absent
      // or untrue; this kills the transfer the moment it exceeds the limit.
      let seen = 0, aborted = false;
      req.on('data', (c) => {
        seen += c.length;
        if (seen > UPLOAD_MAX_BYTES && !aborted) {
          aborted = true;
          req.destroy(new Error('upload exceeded size limit'));
        }
      });
      // stream the multipart body through to ALLM (never parsed here)
      const up = await allm('POST', '/api/v1/document/upload', { headers: { 'content-type': req.headers['content-type'], 'content-length': req.headers['content-length'] }, stream: req });
      if (aborted) return send(res, 413, { error: `file exceeded the ${Math.round(UPLOAD_MAX_BYTES / 1048576)} MB limit` });
      const loc = up.json && up.json.documents && up.json.documents[0] && up.json.documents[0].location;
      if (!loc) return send(res, 502, { error: 'upload failed', detail: (up.json && up.json.error) || up.status });
      const emb = await allm('POST', `/api/v1/workspace/${WS[scope]}/update-embeddings`, { body: { adds: [loc] }, headers: { 'content-type': 'application/json' } });
      if (emb.status !== 200) return send(res, 502, { error: 'uploaded but embedding failed', detail: (emb.json && emb.json.error) || emb.status });
      return send(res, 200, { ok: true, location: loc, scope });
    }
    if (p === '/api/documents/scope' && req.method === 'POST') {
      const { docpath, scope, on } = await readBody(req);
      if (!docpath || (scope !== 'private' && scope !== 'public')) return send(res, 400, { error: 'docpath and scope required' });
      // A missing/malformed `on` must not be silently treated as "off" and
      // detach a document nobody asked to detach (Copilot review, PR #141).
      if (typeof on !== 'boolean') return send(res, 400, { error: 'on must be true or false' });
      const otherScope = scope === 'private' ? 'public' : 'private';
      // Turning this scope off can leave the document embedded in NEITHER
      // workspace — invisible to /api/documents yet still in ALLM's system
      // store: an orphan this UI can never reach again. The whole decision
      // (would-it-orphan? → lock guard → embed change → purge) runs under the
      // mutex so a concurrent lock can't slip between the check and the purge
      // (Copilot review, PR #141).
      const out = await withDocLock(async () => {
        let orphansIt = false;
        if (!on) {
          const other = await docsOf(otherScope);
          // If we can't reliably read the other workspace we cannot tell whether
          // this orphans the document; silently guessing "no" would skip BOTH
          // the lock guard AND the purge. Fail loud instead (Copilot review).
          if (!other.ok) return { code: 502, body: { error: `could not verify ${otherScope} before updating ${scope} — try again` } };
          orphansIt = !other.docs.some((d) => d.docpath === docpath);
        }
        if (orphansIt && readLocked().has(docpath)) {
          return { code: 409, body: { error: 'this document is locked and this is its last active scope — unlock it first' } };
        }
        const op = on ? 'adds' : 'deletes';
        const emb = await allm('POST', `/api/v1/workspace/${WS[scope]}/update-embeddings`, { body: { [op]: [docpath] }, headers: { 'content-type': 'application/json' } });
        if (emb.status !== 200) {
          // Log the upstream detail server-side; don't echo raw ALLM internals
          // back to the client (Copilot review, PR #141).
          console.error('[dashboard] scope update failed:', scope, emb.status, (emb.json && emb.json.error) || '');
          return { code: 502, body: { error: `could not update ${scope}` } };
        }
        if (orphansIt) {
          // Embedded nowhere now — purge from the system store instead of
          // leaving an invisible leak, then drop any stale lock so the lock set
          // doesn't accumulate dead docpaths (Copilot review, PR #141).
          await allm('DELETE', '/api/v1/system/remove-documents', { body: { names: [docpath] }, headers: { 'content-type': 'application/json' } }).catch(() => null);
          const s = readLocked(); if (s.delete(docpath)) writeLocked(s);
        }
        return { code: 200, body: { ok: true } };
      });
      return send(res, out.code, out.body);
    }
    if (p === '/api/documents/delete' && req.method === 'POST') {
      const { docpath } = await readBody(req);
      if (!docpath) return send(res, 400, { error: 'docpath required' });
      // Server-side is the real gate, not just the disabled button — the same
      // invariant as every other guard in this file (CSRF header, upload
      // allowlist, non-emptyable allowed-websites list).
      // Lock check → detach → purge runs under the mutex so a concurrent lock
      // can't land between the check and the purge (Copilot review, PR #141).
      const out = await withDocLock(async () => {
        if (readLocked().has(docpath)) return { code: 409, body: { error: 'this document is locked — unlock it first, then delete' } };
        const detaches = await Promise.all(['private', 'public'].map((s) =>
          allm('POST', `/api/v1/workspace/${WS[s]}/update-embeddings`, { body: { deletes: [docpath] }, headers: { 'content-type': 'application/json' } })
        ));
        const failed = detaches.filter((r) => r.status !== 200);
        if (failed.length) {
          // Log upstream detail server-side; return a generic message rather
          // than echoing raw ALLM internals (Copilot review, PR #141).
          console.error('[dashboard] delete detach failed:', failed.map((r) => (r.json && (r.json.error || r.json.message)) || r.status).join('; '));
          return { code: 502, body: { error: 'could not fully remove this document — it may still be embedded in one workspace' } };
        }
        // Only purge the underlying file once BOTH workspaces confirmed the
        // detach — purging on a partial failure would leave the failed
        // workspace referencing a file that's gone, breaking RAG there while
        // this response claimed success (Copilot review, PR #141).
        await allm('DELETE', '/api/v1/system/remove-documents', { body: { names: [docpath] }, headers: { 'content-type': 'application/json' } }).catch(() => null);
        // Drop any stale lock for the now-deleted doc so the set stays bounded.
        const s = readLocked(); if (s.delete(docpath)) writeLocked(s);
        return { code: 200, body: { ok: true } };
      });
      return send(res, out.code, out.body);
    }

    // ── private chat (proxied; customer never talks to ALLM directly) ──
    // Optional `thread` (an ALLM thread slug) scopes the conversation; without
    // it the workspace's default conversation is used — full back-compat.
    const threadSlugOk = (s) => /^[a-z0-9][a-z0-9-]{0,64}$/i.test(String(s || ''));
    if (p === '/api/chat' && req.method === 'POST') {
      const { message, thread } = await readBody(req);
      if (!message) return send(res, 400, { error: 'message required' });
      if (thread && !threadSlugOk(thread)) return send(res, 400, { error: 'bad thread' });
      const chatPath = thread
        ? `/api/v1/workspace/${WS.private}/thread/${thread}/chat`
        : `/api/v1/workspace/${WS.private}/chat`;
      const r = await allm('POST', chatPath, { body: { message, mode: 'chat' }, headers: { 'content-type': 'application/json' } });
      // An upstream failure must be an error, not a 200 whose "text" is the raw
      // upstream error string — the UI renders {text} as a normal bot bubble.
      if (r.status !== 200 || !(r.json && r.json.textResponse))
        return send(res, 502, { error: (r.json && (r.json.error || r.json.message)) || 'the assistant is unavailable right now' });
      return send(res, 200, { text: stripThink(r.json.textResponse), sources: (r.json.sources || []).map((s) => s.title).slice(0, 5) });
    }

    // ── private chat threads (list / create / history / delete) ──
    if (p === '/api/threads' && req.method === 'GET') {
      const r = await allm('GET', `/api/v1/workspace/${WS.private}`);
      const wsObj = (r.json || {}).workspace;
      const w = Array.isArray(wsObj) ? wsObj[0] : wsObj;
      const threads = ((w && w.threads) || []).map((t) => ({ slug: t.slug, name: t.name }));
      return send(res, r.status === 200 ? 200 : 502, { threads });
    }
    if (p === '/api/threads' && req.method === 'POST') {
      const { name } = await readBody(req);
      // Explicit unique slug instead of letting ALLM derive one from `name`.
      // Thread names come from the first message actually sent (deriveTitle()
      // client-side), so two different conversations easily share a name —
      // e.g. two chats both opening with "How much revenue have we
      // generated?". A name-derived slug would then resolve to the SAME
      // existing thread instead of creating a new one, silently merging one
      // conversation's history into another rather than stacking a new entry.
      const slug = `t-${Date.now().toString(36)}-${crypto.randomBytes(4).toString('hex')}`;
      const r = await allm('POST', `/api/v1/workspace/${WS.private}/thread/new`, {
        body: { slug, name: String(name || '').slice(0, 80) || `Conversation ${new Date().toISOString().slice(0, 10)}` },
        headers: { 'content-type': 'application/json' },
      });
      const t = r.json && r.json.thread;
      if (!t) return send(res, 502, { error: 'could not create the conversation', detail: (r.json && (r.json.message || r.json.error)) || r.status });
      return send(res, 200, { slug: t.slug, name: t.name });
    }
    {
      const tm = p.match(/^\/api\/threads\/([A-Za-z0-9-]{1,64})\/(chats|delete|rename)$/);
      if (tm && tm[2] === 'chats' && req.method === 'GET') {
        const r = await allm('GET', `/api/v1/workspace/${WS.private}/thread/${tm[1]}/chats`);
        const history = ((r.json && r.json.history) || []).map((h) => ({ role: h.role, text: stripThink(h.content) }));
        return send(res, r.status === 200 ? 200 : 502, { history });
      }
      if (tm && tm[2] === 'delete' && req.method === 'POST') {
        const r = await allm('DELETE', `/api/v1/workspace/${WS.private}/thread/${tm[1]}`);
        return send(res, r.status === 200 ? 200 : 502, { ok: r.status === 200 });
      }
      if (tm && tm[2] === 'rename' && req.method === 'POST') {
        const { name } = await readBody(req);
        const clean = String(name || '').trim().slice(0, 80);
        if (!clean) return send(res, 400, { error: 'name required' });
        // Best-effort against ALLM's workspace-thread update route — unverified
        // against a live instance (no ALLM access from this dev environment).
        // If this 502s in practice, confirm the real path/payload and fix here.
        const r = await allm('POST', `/api/v1/workspace/${WS.private}/thread/${tm[1]}/update`, {
          body: { name: clean }, headers: { 'content-type': 'application/json' },
        });
        if (r.status !== 200) return send(res, 502, { error: 'could not rename the conversation', detail: (r.json && (r.json.message || r.json.error)) || r.status });
        return send(res, 200, { ok: true, name: clean });
      }
    }
    // Default-conversation history (the no-thread chat), for parity on load.
    if (p === '/api/chats' && req.method === 'GET') {
      const r = await allm('GET', `/api/v1/workspace/${WS.private}/chats`);
      const history = ((r.json && r.json.history) || []).map((h) => ({ role: h.role, text: stripThink(h.content) }));
      return send(res, r.status === 200 ? 200 : 502, { history });
    }

    // ── authorised websites (the embed's domain allowlist) ──
    if (p === '/api/embed-domains' && req.method === 'GET') {
      return send(res, 200, { domains: readDomains(), always: SELF_ORIGIN ? [SELF_ORIGIN] : [], configured: !!EMBED_ID });
    }
    if (p === '/api/embed-domains' && req.method === 'POST') {
      if (!EMBED_ID) return send(res, 400, { error: 'the chat widget is not provisioned yet — contact WeOwn support' });
      const body = await readBody(req);
      const input = Array.isArray(body.domains) ? body.domains : [];
      const bad = input.filter((d) => String(d || '').trim() && !normOrigin(d));
      if (bad.length) return send(res, 400, { error: `not a usable website address: ${bad.slice(0, 3).join(', ')} — use the form example.com (no wildcards, no page paths)` });
      // Self-origin is always retained, so the list can never become empty —
      // an empty allowlist is exactly the allow-any-site state this prevents.
      const list = dedupe([SELF_ORIGIN, ...input.map(normOrigin)]);
      if (!list.length) return send(res, 400, { error: 'at least one website is required' });
      const r = await allm('POST', `/api/v1/embed/${encodeURIComponent(EMBED_ID)}`,
        { body: { allowlist_domains: list.join(',') }, headers: { 'content-type': 'application/json' } });
      if (r.status !== 200 || !(r.json && r.json.success)) {
        return send(res, 502, { error: 'could not update the allowed websites', detail: (r.json && r.json.error) || r.status });
      }
      const persisted = writeDomains(list);
      return send(res, 200, { ok: true, domains: list, persisted });
    }

    // ── embed snippet ──
    if (p === '/api/snippet' && req.method === 'GET') {
      if (!EMBED_ID) return send(res, 200, { snippet: '', note: 'Embed not provisioned yet — contact WeOwn support.' });
      const d = PUBLIC_DOMAIN || 'YOUR-INSTANCE-DOMAIN';
      // data-greeting carries the AI disclaimer the moment the widget opens, so
      // it is stated before the visitor types anything (PRD §3, non-negotiable).
      const greeting = "Hi! I'm an AI assistant. Everything here is general information only — please verify it for your own situation, and don't share private information in this chat.";
      return send(res, 200, { snippet:
        `<script data-embed-id="${EMBED_ID}"\n` +
        `  data-base-api-url="https://${d}/api/embed"\n` +
        `  data-greeting="${greeting}"\n` +
        `  data-no-sponsor="true"\n` +
        `  src="https://${d}/embed/anythingllm-chat-widget.min.js"><\/script>` });
    }

    return send(res, 404, { error: 'not found' });
  } catch (e) {
    console.error('[dashboard]', e.message);
    send(res, 500, { error: 'internal error' });
  }
});

server.listen(PORT, () => console.log(`dashboard ${VERSION} listening :${PORT} base=${BASE} allm=${ALLM_URL} ws=${WS.public}/${WS.private}`));
