# Generated by Django 5.2.16 on 2026-08-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='instance_status',
            field=models.CharField(choices=[('none', 'No instance'), ('awaiting_provision', 'Being set up'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('paused', 'Paused'), ('retired', 'Retired')], default='none', help_text="Lifecycle of the customer's private instance (operator-driven until provisioning automation lands)", max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='instance_url',
            field=models.URLField(blank=True, help_text="Customer's instance URL once active"),
        ),
    ]
