# Generated by Django 5.2.16 on 2026-08-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_affiliatecontract_signer_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='affiliate',
            field=models.ForeignKey(blank=True, help_text='Referring affiliate at the moment this subscription was created. Customers cannot change this; admins can.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_subscriptions', to='core.affiliate'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.customer'),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.SlugField(help_text='Customer-chosen name; becomes <subdomain>.weown.dev', max_length=40, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('requested', 'Requested (awaiting payment)'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('paused', 'Paused (billing)'), ('destroying', 'Destroying'), ('destroyed', 'Destroyed')], default='requested', max_length=16)),
                ('provision_log', models.TextField(blank=True, help_text='Latest provisioning output/status detail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.customer')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance', to='core.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
